### ISSUE TITLE
Background color on selected item is not updated in splitview on go back

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#412] opened 2017-05-26 10:05 UTC
Repro: 
1. Create new project with projectType SplitView
2. Add various pages
3. Generate 
4. Navigate to any page
5. Go back

Actual result:
![image](https://cloud.githubusercontent.com/assets/24698018/26490275/f0fce556-420a-11e7-859e-ad44369a79bc.png)
The yellow background remains on the previously selected page, the yellow bar is on the currently selected page

Expected result: 
Yellow background and yellow bar should be on the currently selected item

**Comment by touseefbsb** [comment] 2017-05-26 13:20
I was about to report the same bug. I can confirm I am having the same bug. Also the first time app is launched it is navigated to homepage and within listview home is not selected ( not highlighted ) but it does have left border to indicate the selection. But when user selects any other page then the listviewItem gets highlight as well.
So the experience is not consistent for the user, either make homepage highlighted at first start as well, or remove highlight totally for all items in navigation because maybe the left border alone is good enough indication for the selected page, just a suggestion :)

**Comment by touseefbsb** [comment] 2017-05-26 13:29
this might be out of scope of this issue or bug but can someone please tell me how to change the background of the selected listview Item? I only want the left border/rectange to indicate the selected navigation menu and I dont want any background at all on the selected item. How can I access the ListView within the navigation pane? so that I can achieve this? Thanks

**Comment by touseefbsb** [comment] 2017-05-26 13:48
nevermind I figuered it out, just edited the template with blend and I was able to edit style of ListView.ItemContainerStyle

**Comment by mrlacey** [comment] 2017-05-26 16:26
I don't believe we should have the full background section highlighting as it makes the accent color image/text on accent colored semi-transparent background hard to read.
We have the foreground color change and the indicator rectangle to show the current item.
The background color that isn't set correctly in this bug is a consequence of the default behavior of the toolkit control. It's hidden from all their samples as they set a background color and not something they're likely to change based on https://github.com/Microsoft/UWPCommunityToolkit/issues/969

**Closed by mrlacey** 2017-05-26 16:26 UTC
Labels: bug

**Comment by crutkas** [comment] 2017-05-26 17:28
my opinion it should work like the NavigationView pending in FCU.  If there is a bug in the UWP Toolkit control, we report it there and let them deal with the issue (if appropriate, submit a PR) and we get it via a nuget update.

**Comment by touseefbsb** [comment] 2017-05-26 17:54
@crutkas  yes that is exactly what I am suggesting that it should look like and behave like NavigationView in FCU

**Comment by mrlacey** [comment] 2017-05-26 19:26
@crutkas it's not a bug it's just default behavior which they recognize as not being ideal but won't change. They want people to update the UI if they want something different--like we do.

**Comment by crutkas** [comment] 2017-05-26 20:37
@nmetulev hey, looks like the hamburger menu has a bug but   Is this something we can get fixed or are you guys going to live with the behavior until FCU?

**Comment by skendrot** [comment] 2017-05-26 20:39
As @mrlacey mentioned, it's not a bug. But we would like to get the two looking the same. A [new issue](https://github.com/Microsoft/UWPCommunityToolkit/issues/1185 )has been opened to address this

**Comment by nmetulev** [comment] 2017-05-26 20:44
Agree with @skendrot , we should get the two looking the same. @crutkas, feel free to submit PRs to the toolkit to update the menu for things you need urgently. Otherwise, we will plan to have it updated for 1.5 or 2.0
