### ISSUE TITLE
Iterating between Maps / Camera

### ISSUE THREAD

**Issue by Pinox** [Microsoft/WindowsTemplateStudio#2360] opened 2018-06-09 12:13 UTC
I have noticed that iterating very fast between the maps and camera page causes the app to crash.

VS 15.7.3 Stable
Windows 10 Pro - Version 1803

![ts_version](https://user-images.githubusercontent.com/5297255/41191407-3a63fd42-6bef-11e8-8f1a-a4921b42802d.PNG)

![ts](https://user-images.githubusercontent.com/5297255/41191408-3c767a06-6bef-11e8-820f-0a4029aaad78.PNG)

**Comment by crutkas** [comment] 2018-06-09 17:17
Can you provide a stack on the crash?

**Comment by crutkas** [comment] 2018-06-10 07:37
@sibille this feels like the camera hasn't fully shut down and is still in use when a use would bring it back up.  Do we have logic to catch this?

**Comment by sibille** [comment] 2018-06-10 19:15
We'll have a look at it.

**Comment by sibille** [comment] 2018-06-11 06:45
@Pinox, which framework did you use to create the application?

**Comment by Pinox** [comment] 2018-06-11 08:45
@sibille  , I used the latest framework.  Looks like the crash happens when the init of the camera is still busy.    I flagged this as I can see this being an bigger issue on lower specked devices/pc's or slower device drivers where the camera is still busy and trying to initiate.

**Comment by sibille** [comment] 2018-06-11 09:06
Thanks @Pinox !

**Comment by dgomezc** [comment] 2018-06-19 15:10
The problem is that the camera resource is initialized and released in the Loaded and Unloaded events of the CameraControl control.

There are cases in which the Loaded event of the control of the page to which we navigate is triggered, before the Unloaded event from the page from which we are navigating, so it tries to initialize the camera resource before releasing it.

To fix this, it is necessary to release the camera resource during navigation in the OnNavigatingFrom event and initialize the camera resource in the OnNavigatedTo event.

In Pivot type projects, these events are not triggered when changing pivot, so we must subscribe to the SelectionChanged event of the pivot, and initialize or release the camera depending on the pages involved in the navigation.

To simplify the code, we have thought of introducing a Helper for this project type, which is initialized when the application is started, receives the pivot, subscribes to the pivot SelectionChanged event, filters the pages involved in the change of the tab and launches an own event indicating those pages. 

A simplified version of the helper would be like this:

```csharp
public class PivotNavigationHelper
{
    private static Pivot _pivot;
    public static event EventHandler<PivotNavigationEventArgs> OnPivotNavigation;

    public static void Initialize(Pivot pivot)
    {
        _pivot = pivot;
        _pivot.SelectionChanged += pivot_SelectionChanged;
    }

    private static void pivot_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        var fromPage = e.RemovedItems.Cast<PivotItem>().Select(p => p.FindDescendant<Page>()).FirstOrDefault();
        var toPage = e.AddedItems.Cast<PivotItem>().Select(p => p.FindDescendant<Page>()).FirstOrDefault();
        
        var eventArgs = new PivotNavigationEventArgs(fromPage, toPage);
        OnPivotNavigation?.Invoke(sender, eventArgs);
    }
}
```


On the camera type pages we would use the helper:

```csharp
public sealed partial class CameraPage : Page, INotifyPropertyChanged
{
    public CameraPage()
    {
        InitializeComponent();
        PivotNavigationHelper.OnPivotNavigation += OnPivotNavigation;
    }

    private async void OnPivotNavigation(object sender, PivotNavigationEventArgs e)
    {
        if (e.FromPage is CameraPage)
        {
            await CameraControl.CleanupCameraAsync();
        }

        if (e.ToPage is CameraPage)
        {
            await CameraControl.InitializeAsync();
        }            
    }
    ...
}
```

At the moment we can add this helper when generating a camera page, and we should use it in the MediaPlayer page too because this page need to stop or start video in the same events.

**Comment by mrlacey** [comment] 2018-06-19 20:33
Rather than adding an app level helper class and having each "page" have to handle every navigation to and from a tab, have you considered adding attached properties on the `PivotItem` (or the View within them) that take commands to activate when navigating to or from that item?
The difference would be between a view saying "tell me when any navigation occurs and I'll work out if I need to do something" (what you're proposing) and the view saying "tell me when these specific events happen, so I can do the extra work I need."

I haven't looked at how best to implement this 

```
    <PivotItem x:Uid="PivotItem_Camera">
        <Frame>
            <views:CameraPage
                PivotExtensions:OnNavigatedTo="{OnNavigatedToCommand}"
                PivotExtensions:OnNavigatedFrom="{OnNavigatedFromCommand}"
                />
```

It'll probably need extra hooks into the Pivot itself and maybe the extension may also need a reference to the PivotItem it's in.
I prefer this approach as the View doesn't need to know about its container, instead, it can ask to be told when specific situations occur.

"Helper" classes tend to have a smell that the coupling is not quite right and I don't like the inclusion of global static classes if they can be avoided.

**Comment by mvegaca** [comment] 2018-06-21 15:03
Here is a PoC with a Pivot Behavior approach (Added in XAML Pivot instance) that will allow us tu run code on pages when a page is selected on unselected in Pivot.
[PivotAppPoC.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/2124177/PivotAppPoC.zip)

I tried using attached Properties but I couldn't find a good solution. This Behavior solution was inspired by current behavior added in Prism Pivot projects.

**Comment by mvegaca** [comment] 2018-06-29 11:20
PR added #2416

Comment on Prism/TabbedPivot
We had to change the prism behaviour, as this was using PivorItemLoading/Unloading and had the same issues with camera and mediaplayer. We changed the behaviour to use SelectionChanged

**Comment by dgomezc** [comment] 2018-07-31 09:30
Verified in dev-nightly:
Templates version: 0.18.18212.2
Wizard version: 0.18.18212.1

**Closed** 2018-07-31 09:30 UTC
Labels: bug
