### ISSUE TITLE
Feature: What's new in this version

### ISSUE THREAD

**Issue by myokeeh** [Microsoft/WindowsTemplateStudio#457] opened 2017-06-15 04:18 UTC
This is another thing that I think is not done enough or inconsistent across Microsoft first-party apps.

After an update, I think it's nice to know what's new in the version.

Specifically, a control/page that presents the information.

**Comment by myokeeh** [comment] 2017-06-15 04:25
I guess this is similar to #296

**Comment by mrlacey** [comment] 2017-06-15 09:47
Yes, a duplicate of #296 
I want to add this functionality to WTS to help developers avoid the excuse for not doing it.

**Closed by mrlacey** 2017-06-15 09:47 UTC
