### ISSUE TITLE
Mediaplayer - Pausing video

### ISSUE THREAD

**Issue by Pinox** [Microsoft/WindowsTemplateStudio#1757] opened 2018-01-29 08:56 UTC
Pausing the media player and then moving to another view and returning back to media player view causes the media player freeze. (unable to restart the media player)

Running latest version VS2017 and latest version Template studio

**Comment by mrlacey** [comment] 2018-01-29 19:17
With the latest preview releases (VS & WTS)   
If selecting a Tabs&Pivot project type, The first time you go to the media player tab the video will start automatically. If you switch to another tab it will pause the video. On returning to the media player tab the video will not restart automatically but will require you to press the play button for it to resume.

This works as intended for me.

**Comment by Pinox** [comment] 2018-01-29 21:31
plse find attached the repo.  Not using preview version, so just reporting the issue that I see.
Can't restart the player after moving to another page.  (with / without pause before moving to another page)

[MediaPlayerFreeze.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/1675310/MediaPlayerFreeze.zip)

**Comment by mrlacey** [comment] 2018-01-30 11:05
**Repro**

Create a new app
- ProjectType: Navigation View
- Framework: MVVM Light
- Add one MediaPlayer page
- Run generated app.

**Expected**
Can open and close the media player page as many times as like and play video each time.

**Actual**
Only possible to play the video the first time the page is loaded.

_I'm continuing to investigate_

**Comment by mrlacey** [comment] 2018-01-30 12:12
I'm able to reproduce inconsistently with the v1.7 pre-release version.

Unable to reproduce with MVVMBasic.

**Comment by ralarcon** [comment] 2018-01-30 15:09
@mrlacey, @dgomezc can have a look on this too... just to be sure that the changes introduced for the Pivot does not have a side effect here (I don't think so, but just to double check).

**Comment by mrlacey** [comment] 2018-01-30 15:51
The issue is that the ViewModelLocator (VML) only ever creates a single instance of the MediaPlayer view model and this persistence holds a reference that stops multiple MediaPlayer instances from working correctly.

**workaround**

The simplest solution is to force the VML to always provide a new instance of the ViewModel by requesting it with a unique key each time.  Modifying the VML code to match the below will do it.

`public MediaPlayerViewModel MediaPlayerViewModel => ServiceLocator.Current.GetInstance<MediaPlayerViewModel>(Guid.NewGuid().ToString());`

There are potentially negative sided effects to doing this, depending on what else the code is modified to do.  
If we use this as a solution and change the templates to reflect the above this will make the way the VML handles this VM differently to all the others. **Do you think that a comment explaining that and why the VM lifetime is different will be sufficient?**

This does not impact the use of the media player page in a pivot app as that manages page (and VM) life-times differently.

I've verified the other frameworks and this only impacts MVVMLight.

**Comment by mrlacey** [comment] 2018-01-31 13:20
> Do you think that a comment explaining that and why the VM lifetime is different will be sufficient?

any objections to this approach?

**Comment by mrlacey** [comment] 2018-02-01 21:15
Lack of objection is being treated as tacit approval and so I'm continuing with this.

**Comment by ralarcon** [comment] 2018-02-02 08:42
Sorry, @mrlacey, I absolutely agreed including the comment and I thought I answered.

**Comment by crutkas** [comment] 2018-02-02 13:34
Hot fix?

**Comment by mrlacey** [comment] 2018-02-02 13:45
If we do a hotfix next week (primarily for #1774) then it should include all template fixes and so it would include this.   
Assuming that the hotfix will be templates only.

**Comment by mrlacey** [comment] 2018-02-04 15:36
Verified in 
Wizard: 0.16.18035.1
Templates: 0.16.18035.1

Keeping open until hotfix released

**Comment by ralarcon** [comment] 2018-02-05 14:08
@mrlacey, @crutkas: do we want to deliver a hotfix just for this or would include all changes we have pending in dev (most of them are related to templates improvements).

If delivering all we currently have in dev, just need to know if the changes done by @mrlacey within the extension to templates icons loading are required to be deployed too or are optional.

**Comment by mrlacey** [comment] 2018-02-05 16:54
I vote for a hotfix to release newer templates with the latest fixes which affect VB & MVVMLight/C#.

The fix for the icons was in the wizard code, not in the templates, and so won't be part of the hotfix.

**Comment by ralarcon** [comment] 2018-02-05 17:02
Good, in that case, we will prepare a hotfix with all currently in dev (easy, by the way). Tomorrow morning CET we will merge dev to master and set up the hotfix. By the way, @sibille, we should block the automatically PRE-release generation to avoid deliver the extension bits before we test it with current pre-release version (same conditions will be in pro).

**Comment by sibille** [comment] 2018-02-05 17:09
Continuos integration for pre vsix disabled.

**Comment by sibille** [comment] 2018-02-07 08:34
Hotfix released:
Wizard: 1.7.18030.1
Templates: 1.7.18037.1

**Closed by sibille** 2018-02-07 08:34 UTC
Labels: Can Close Out Soon, Generated Code, MVVMLight, bug, done
