### ISSUE TITLE
New project will not run

### ISSUE THREAD

**Issue by mjmeans** [Microsoft/WindowsTemplateStudio#310] opened 2017-05-12 01:35 UTC
Installed WTS. Created new app with hamburger navigation, mvvm light. Run. FAIL. I get "the process exited with a native exception". I made no changes, I just tried to run the app immediately after creating it using WTS.

**Comment by mrlacey** [comment] 2017-05-12 02:51
@mjmeans Does this happen every time? Even with restarting VS?
Any exceptions listed?
Is anything in the output window with more exception information?
What's the version of VS you have installed? (The full number, including the bit in brackets, from Help > About...)

**Comment by mjmeans** [comment] 2017-05-12 08:45
Even restarting VS. Even restarting Windows. Winver is 1703 (Build 15063.296). VS ver is 15.2 (26430.4) Release. Output window is not visible when the error pops up. VS is stuck until closing the error message pop-up. Immediate window shows "Activation of the Windows Store app 'blah' failed with error 'The app didn't start'.

**Comment by mjmeans** [comment] 2017-05-12 09:18
Additional info in Application event log ... 'See the Microsoft-Windows-TWinUI/Operational log for additional information.'

Additional info in Microsoft-Windows-TWinUI/Operational log ... Activation via contract helper of the app E9B7957F-6E73-4168-9755-92604583D09D_73zwdfx56gv16!App for the Windows.Launch contract failed with Server execution failed.

**Comment by mrlacey** [comment] 2017-05-12 19:11
@mjmeans can you try building an app with the 'Blank App' template and see if that works
![image](https://cloud.githubusercontent.com/assets/189547/26012919/071bf1d4-370b-11e7-963d-ec0f7a096cfe.png)

My guess is that it's a problem with the UWP SDK install and not WTS related. 
If building a blank app fails then try reinstalling the SDK.
If building a blank app works then we can investigate further. Start by checking you can run apps installed from the store.

**Comment by mjmeans** [comment] 2017-05-12 19:32
Blank App doesn't work as you suspected.

More information: Prior to installing any VS 2017 components the machine has already installed several VS versions: 2010 Pro, 2012 Prem, 2013 Pro, 2015 community. VS 2017 was installed automatically by the Unity for VS 2017 installer which was installed on 5/9. The machine has had several reboots since then. I am now trying to install VS 15.2 update and will test again. But Q: How do I manually uninstall and reinstall only the UWP SDK from VS 2017 without affecting any other version of VS?

**Comment by mjmeans** [comment] 2017-05-12 20:02
I'm using the VS 2017 installer "individual components" list to remove and reinstall USM SDK.

**Comment by mjmeans** [comment] 2017-05-12 22:28
Unfortunately still fail after reinstall UWP SDK form VS 2017 installer. I even tried adding Core and Xamarin and some SQL tools. I even tried downloading reinstalling the Win 10 Creators SDK.

**Comment by mrlacey** [comment] 2017-05-12 22:59
@mjmeans I can't find any conclusive solutions to this online. I find several people reporting this and for built-in apps as well as ones they're building. Some people have resorted to reinstalling the OS or have addressed it with admin issues.
If you still have VS2015 installed you could try building a universal app and seeing if that still works. I'm not sure what else to suggest apart from repeating whatever others have suggested in results when searching for the error message.

**Comment by mjmeans** [comment] 2017-05-12 23:39
I have confirmed that a store app written in VS 2013 and updated to VS 2015 Community targeting Windows 8.1 does deploy and debug in Windows 10 Creators update. So the problem is not related to the store.

I have confirmed that VS 2015 Community can create a blank UWP app, build, deploy; but it also has the same error. The last time I ran a VS 2015 UWP app on this machine was several months ago when I was experimenting with Windows 10 IoT Core on Raspberry Pi and desktop platforms.

I don't believe that you can conclude that the cause is an external issue at this time. It seems to me that you just assume the cause is external without actually proving it.

Reinstalling the OS is not an option. It would literally take days to reinstall and configure all applications and development tools on this machine.

**Comment by mjmeans** [comment] 2017-05-13 03:55
I believe I have discovered the issue. The template doesn't set the check box in the build properties to "Compile with .NET Native tool chain". Once I set manually checked that on a UWP VS 2015 Blank project it worked. So I checked to see if that box was set on the VS 2017 WTS project. It wasn't! So I checked it and it compiled and ran with settings MinVer 14393 and TargetVer 15063.

**Comment by mrlacey** [comment] 2017-05-13 05:14
I changed the label to 'external-issue' as the problem isn't specific to WTS, it happens when you build and run any UWP created app.
It is not and should not be a requirement that the app is compiled with .NET Native to be able to run or debug on your local machine. There is nothing in the generated code to require this.
Because of the time the .NET Native tools take to run and because they can make debugging more challenging, they are not enabled for the DEBUG configuration. They are enabled for the RELEASE configuration as they should be used when compiling for the store.

It's good to know that you have identified the issue and a workaround so I'll close this issue, but the problem still suggests an underlying issue with the UWP SDK on your machine.

**Closed by mrlacey** 2017-05-13 05:14 UTC
Labels: external-issue

**Comment by mjmeans** [comment] 2017-05-13 05:42
Some other new information. When I set the platform target to x86, it requires native toolset to activate the UWP app. However, when I set the platform to x64 it runs without setting the native toolset!
