### ISSUE TITLE
Non obvious template ordering

### ISSUE THREAD

**Issue by nigel-sampson** [Microsoft/WindowsTemplateStudio#909] opened 2017-08-05 11:32 UTC
While working on the [Caliburn,Micro](https://github.com/Microsoft/WindowsTemplateStudio/tree/Caliburn.Micro) templates I came across an interesting issue that could be a problem or could be limited understanding of how the system should work 😄 .

As part of the [project template](https://github.com/Microsoft/WindowsTemplateStudio/tree/Caliburn.Micro/templates/_composition/CaliburnMicro/Project) I've completely overridden [`ActivationService`](https://github.com/Microsoft/WindowsTemplateStudio/blob/Caliburn.Micro/templates/_composition/CaliburnMicro/Project/Services/ActivationService.cs) since there are significant differences between it and the default. Generate of the project appears to be working correctly.

However when adding support for a number of features I noticed that modifications to the `ActivationService` by the feature template were not being applied. It appears the order the templates are being applied is (using FirstRunPrompt as the example).

1. Projects/Default
2. Features/FirstRunPrompt 
3. _composition/CaliburnMicro/Project

This means that the changes made to `ActivationService` made by `2.` are being overwritten by `3.`, this felt unintuitive to me thinking the framework modifications to the project would be applied to the project before any feature or pages.

This leads to a few questions.

1. Is the assumption about ordering correct and this is a bug?
2. Is there are way to influence ordering?
3. Should templates in _composition not be overriding files? I can see why this would not make sense to do for Pages and Features, but frameworks may be the odd one out here.

**Comment by mrlacey** [comment] 2017-08-07 12:36
@nigel-sampson 2 things here that are probably affecting you. 
1. The order that "templates" are applied is determined by the order they exist on disk, not anything else. This worked fine (by happy coincidence) for everything previously by I also hit issues with this when looking at VB support, I had to add an order tag to the templateInfo instances to control the order they are processed in. I suspected it might be needed for other things and it might be that you've also hit this.
2. The current FirstRunPrompt (like most of the service features) builds upon code that is included by default in the other project types. If the base Caliburn project won't include this we'll need different versions of impacted features.

(Quick response, I will hopefully look at things further in the coming week but this may 🤞 unblock you a bit.)

**Comment by nigel-sampson** [comment] 2017-08-08 03:52
Sounds good.  So far the impact has been really light and its only because the template `3.` is doing a wholesale replacement of a file from `1.`.

This does raise the question whether these composition templates should be doing file replacement like that. I'm wondering if I can turn it into a _postaction by having it remove the constructor and method I don't want to add in the ones I do. But this feels fragile If I have to include the whole of the code I want removed.

**Comment by mrlacey** [comment] 2017-08-08 07:44
Use replacements/deletions with great care.
Generally, you should use composition to add more code. If you're wanting to remove something another feature has put in, that suggests a different structure may be needed.
The only place we use deletions in the current templates is just with some minor tidying up.
Can you share an example of what the issue is / or what you're doing?
There are a few small places where multiple pages/features may both want to do the same thing and I have #294 (& a PoC solution) for handling that.

**Comment by nigel-sampson** [comment] 2017-08-08 22:42
Thanks, that's the impression I got from browsing the existing templates.

My current version of the [`ActivationService`[(https://github.com/Microsoft/WindowsTemplateStudio/blob/Caliburn.Micro/templates/_composition/CaliburnMicro/Project/Services/ActivationService.cs) has a substantially different constructor and `ActivateAsync` so I did a full replacement in the template. This is where the ordering issue comes up as the replacement is happening after say the `ActivationService_postaction.cs` for First Use Prompt is applied.

**Comment by mrlacey** [comment] 2017-08-12 09:27
With the VB code now in dev you can set the "wts.order" tag in a template (like [here](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/templates/Features/SuspendAndResumeVB/.template.config/template.json)) to control the order TemplateInfo instances are processed. Anything without an order value is treated as having Int.Max. This allows you to control the order things are processed when it matters or the default order isn't correct.

The above linked item is set to an order of 2 and the [item it has a dependency on](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/templates/Features/SettingsStorageVB/.template.config/template.json) is set to 1. This ensures the thing it wants to modify is already there.


You can set multiple items to the same order value if there's no dependencies between them. I recommend not setting this tag unless you really need to.

**Comment by nigel-sampson** [comment] 2017-08-23 11:33
Thanks, sorry for the delay in getting back on this one. 

Creating a new blank project using the First Run Prompt feature shows the following templates in the given order in the log.

1. Default (order set to 1).
2. Blank (order set to 1).
3. First Run Prompt (order set to 5).
4. Settings Storage (order set to 1).
5. CaliburnMicro.Project (order set to 2).
6. CaliburnMicro.Page.Blank.AddNavigation (no order set).
7. CaliburnMicro.Page.AddViewModel (no order set).

Looking the source it appears we're only applying the ordering to the composition templates and to nothing else which doesn't allow the template to insert itself into the correct order.

A quick hack to replace [this line](https://github.com/Microsoft/WindowsTemplateStudio/blob/master/code/src/UI/Generation/GenComposer.cs#L124) to `return genQueue.OrderBy(g => g.Template.GetOrder());` works but may have some affects I haven't yet tested or this may not be what you intended with adding that tag.

Thanks.

**Comment by sibille** [comment] 2017-09-06 14:45
The wts.order tag is used in the wizard to establish a visual order of the items (pages and features) in the wizard, I think we should not use the same tag to order the generation queue. 

I'll have a look at the code that composes the generation queue to see if we can add the composition templates right after the template that triggered its addition, to generate a queue like this one:

1. Default Project Template
2. Default Project Template compositions
3. Blank
4. Blank compositions
5. First Run Prompt 
6. First Run Prompt compositions

 @mrlacey I think your issue could be solved with a more "intelligent" generation queue too, adding dependency templates above the depending templates in the queue, what do you think?

**Comment by nigel-sampson** [comment] 2017-09-06 20:47
@sibille it appears from [this line](https://github.com/Microsoft/WindowsTemplateStudio/blob/master/code/src/UI/Generation/GenComposer.cs#L187) that the `wts.order` tag is being used as part of the generation queue at the moment but only for the composition templates and not the project / page or feature templates.

**Comment by mrlacey** [comment] 2017-09-06 21:27
I believe that was me.
Templates were executed in the order they were added which defaulted to the order they were returned by the file system, which was alphabetical.
Because of the naming system for the VB versions, this meant that just using the naming order didn't work and so I had to use the order to control execution order.

From the listings in the image below, You can see that `Project.SplitView` comes before `Project.SplitView.AddToPrimaryNavigationItems` and so was executed first which is good because the "AddToPrimaryNavigationItems" assumes files it wants to modify have already been added to the project by the first. With the VB versions of these folders (VB suffix on the end of the name), it tries to merge with files which haven't yet been added. (Side note. Error messages and information to help debug such an issue are sparse, to say the least, and we may need to improve this when support for custom template sources is added.)

![image](https://user-images.githubusercontent.com/189547/30135048-48d07b3e-9351-11e7-9375-908e96519ea6.png)


We had the "order" property that wasn't being used for these templates and so I reused it. Doing this was my way of controlling the order of generation. 

Might it be better to remove the "wts.order" Tag and replace it with "wts.displayOrder" and "wts.generationOrder" so it's clearer what each does, and why, and we don't have any issues with templates that need both?

**Comment by ralarcon** [comment] 2017-09-07 07:54
I like to use two new tags but I would suggest to let "wts.order" for generation ordering and add the new "wts.displayOrder" to be used in the wizard. This ensure backward compatibility with existing templates (or people implementing templates). Currently "wts.order" is almost ignored and we control the wizard to use the "wts.displayOrder".

Other option is to handle the compatibility in the code and use the tags "wts.order" or "wts.generationOrder" to be the generation order...

**Comment by mrlacey** [comment] 2017-09-07 10:33
@ralarcon I don't like the idea of keeping "wts.order" as it is general. "displayOrder" and "generationOrder" are specific. Even on their own, it's clear what they are for. "Order" on its own does not indicate what it is the order of or how it will be used.

If these were functions you wouldn't call them `SortByOrder()` and `SortByDisplayOrder()` because it's not clear what is used for the order in the first. 
The same principle applies here. If you have two similar or potentially related things, give them both specific names to avoid any potential confusion. 
With the methods  `SortByGenerationOrder()` and `SortByDisplayOrder()` it becomes clear that there are two different ways of ordering things and what they are.

**Comment by ralarcon** [comment] 2017-09-07 10:40
You are right and agree with your explanation so we can handle the compatibility... I was just pointing the issue we would have if someone forget to change wts.order to wts.generationOrder this, if i'm not wrong is not possible to be "detected" as it will not rise any exception / error reading the templates.

Agree with renaming. We need to make it clear and be aware of handling possible "wts.order" tags

**Comment by mrlacey** [comment] 2017-09-07 12:20
> if someone forget to change wts.order to wts.generationOrder this, if i'm not wrong is not possible to be "detected" as it will not rise any exception / error reading the templates.

#1037 will handle this, and includes a new test which can catch this. I'll hopefully finish it tonight but waiting for 1.3 to be done first so don't interfere with what's going on in the dev branch and the PR will include fixing up some minor issues in the existing templates that I don't want to get confused with the current release.

**Comment by sibille** [comment] 2017-09-07 12:43
I prepared a PoC [here](https://github.com/sibille/WindowsTemplateStudio/tree/poc_reordergenerationqueue) to see if we can compose the generation queue in the following way. 
The two changes I did were:

- Dependency templates are added before the template that triggered the dependency.

- Composition templates are added right after the template that triggered the addition of the composition item.

The composition items are ordered by wts.order (as it is a poc I did not change the name for the moment), I'd suggest to call the property wts.compositionOrder (it is used only to order the composition templates). The principal template order can be controlled by dependencies where necessary. 

I merged your Caliburn.Micro branch into my PoC and it seems to unblock your issue. 

If everybody agrees with this approach I'll prepare a PR with this approach to compose the generation queue once we shipped 1.3.

**Comment by nigel-sampson** [comment] 2017-09-07 20:43
That makes sense, if we can get away from manually manipulating order then there's less chance of me stuffing it up :smile:

**Comment by mrlacey** [comment] 2017-09-08 00:29
It looks good. Part of me doesn't like that we have two different factors influencing the order in different places, but the alternatives (everything needing dependencies or adding explicit order values where dependencies already imply an order) seem worse.

**Closed** 2017-10-11 10:33 UTC
