### ISSUE TITLE
Local build failing to delete template directory

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#625] opened 2017-07-06 03:15 UTC
File isn't open.  A restart to VS didn't solve it.  I could manually delete

[20170705 08:09:43.026]	crutkas	13808(8)		Verbose	Templates content extracted to C:\Users\crutkas\AppData\Local\Temp\wgk35s5p.e15.
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
[20170705 08:09:43.280]	crutkas	13808(8)		Warning	The folder C:\ProgramData\WindowsTemplateStudio\Templates\Local\0.0.0.0 can't be delete. Error: Access to the path 'description.md' is denied.	Exception:

System.UnauthorizedAccessException: Access to the path 'description.md' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Microsoft.Templates.Core.Fs.SafeDeleteDirectory(String dir) in C:\Users\crutkas\Source\Repos\NewRepo\code\src\Core\Fs.cs:line 124

**Comment by ralarcon** [comment] 2017-07-06 11:43
Getting UnauthorizedAccessException from the File system can be caused by the process trying to write and delete at the same time since the Local VSIX is the only one who "overwrittes" the existing folder... I'm going to try to lock the deletion and avoid to start being copied content while the a deletion in in progress...

**Comment by ralarcon** [comment] 2017-07-06 13:18
The root cause is that currently it is possible to initiate multiple content updates which leads to the collisions... fixing it to avoid multiple content updates at the same time.

**Comment by ralarcon** [comment] 2017-07-06 13:21
Related too with #614

**Comment by ralarcon** [comment] 2017-07-06 13:51
Fixed in PR #638

**Comment by dgomezc** [comment] 2017-09-01 10:58
Checked on version:
Wizard: 0.14.17244.65002
Templates: 0.14.17244.2

**Closed by dgomezc** 2017-09-01 10:58 UTC
Labels: bug, Can Close Out Soon
