### ISSUE TITLE
.net framework needed

### ISSUE THREAD

**Issue by FIVIL** [Microsoft/WindowsTemplateStudio#2102] opened 2018-03-28 23:30 UTC
hi, im using vs2017 and i have latest version of .net core sdk and .net frame work but i cant build any project, it create templates and all but when i hit run i get this error 

"One of your dependencies requires the .NET Framework, but the .NET Framework could not be found in the NuGet packages installed in this project.  Please install the appropriate .NET Framework packages required by your dependency."

**Comment by touseefbsb** [comment] 2018-03-29 09:30
Please make sure you have installed the **Universal Windows Development** segment in your visual studio 2017. to be sure that u have this, within VS 2017 go to Tools -> Get Tools and Features.
This will open your installer again and make sure that uwp package is checked, if it is not please check it and update your visual studio.

**Comment by touseefbsb** [comment] 2018-03-29 20:00
@crutkas  when we make a project with wts ( recent versions ) we have to choose .NetFramework version which is below where we put the solution name. but this is not asked if we create a blank template ( default uwp template which comes with VS, and not with WTS ). I guess his VS installation lacks .Net Framework so maybe thts why he is getting the error

**Comment by crutkas** [comment] 2018-03-29 22:02
@FIVIL weird, i just popped it on my puter from github and it compiled like a champ.  Let me go ask a few people if they have seen something like this.

![image](https://user-images.githubusercontent.com/1462282/38115761-0e26c518-3362-11e8-81f3-f88abc9d128e.png)

**Comment by crutkas** [comment] 2018-03-29 22:04
@FIVIL if you did a file->new blank template, can that compile for you?  target FCU as target, CU as min

**Comment by FIVIL** [comment] 2018-03-29 22:10
@crutkas  well i did that, FCU target and CU as min and it works fine
![capture](https://user-images.githubusercontent.com/31272779/38116062-b600dcf4-33c3-11e8-9599-5a2ca62a4e10.PNG)

**Comment by mrlacey** [comment] 2018-03-30 11:47
@FIVIL In attempting to identify what may be different between the blank project created when you do a regular "File>New Project" and what is produced by WTS. I wonder if it could be due to the version of UWP NetCore library that is referenced. 
Blank UWP projects produced with VS 15.6.4 use version 6.0.8, while the WTS templates you're using target 6.0.6. In theory, there should be no breaking change between these versions but if your machine was not used to build any UWP apps with older versions of the library this may be what's missing.

There are a couple of things you can do to test this.
1. Take the generated project (that is not working) and update and restore all referenced NuGet packages and then try and run it.
2. Use WTS to generate an app that uses the **Blank** project type and the **Coded Behind** framework. Then look at the difference between the two generated solutions. (As creating an app without WTS works on your machine, the reason for WTS generated apps not working will be due to differences between the generated output.) If you can't see a difference, please share both projects and I'll take a look.

Either way, please share how you get on.


_Aside: I'll make sure the templates reference the latest version of the library in their next update._

**Comment by FIVIL** [comment] 2018-03-30 19:05
@mrlacey  i updated nuget packages and now im getting this error and not only me but other person getting this exact error too 
https://github.com/Microsoft/WindowsTemplateStudio/issues/2107
![image](https://user-images.githubusercontent.com/31272779/38150091-99e4ec68-3472-11e8-852e-909c685f4900.png)
also i made a repo for WTS black app with code behind and normal UWP here
this is WTS:
https://github.com/FIVIL/WTS
and this is normal blank UWP:
https://github.com/FIVIL/UWP

**Comment by mrlacey** [comment] 2018-03-30 19:44
@FIVIL See [here](https://github.com/Microsoft/WindowsTemplateStudio/issues/2107#issuecomment-377604466) for the fix for the issue when updating the toolkit version.
If you make that change, does the app now build and run?

**Comment by FIVIL** [comment] 2018-03-30 21:05
@mrlacey  well i did that and now im back to square one then again it says "One of your dependencies requires the .NET Framework, but the .NET Framework could not be found in the NuGet packages installed in this project.  Please install the appropriate .NET Framework packages required by your dependency."
but im sure that all the nugets are updated as you can see here:
![capture](https://user-images.githubusercontent.com/31272779/38153786-b49b0ebe-3483-11e8-8dfd-e15aeb7031b3.PNG)
and in here you can see the changes that i made in shellpage.xaml.cs
![capture](https://user-images.githubusercontent.com/31272779/38153814-d5b3b826-3483-11e8-824a-59ac5860b03f.PNG)

**Comment by mrlacey** [comment] 2018-03-30 21:54
@FIVIL we're not "back to square one." We've ruled out what I thought was the most likely cause of the issue.

Have you tried turning on verbose logging to see if it will tell you more about the error? (Under Tools – Options – Projects and Solutions – Build and Run, there’s the MSBuild project build output verbosity combo box. Set this to Diagnostic and rebuild the project.)
If that doesn't give you anything:

In that a blank UWP project works on your machine but a blank WTS one doesn't it must be due to something different between the two project configurations.
Can you generate a WTS project with **Blank** project type and **CodeBehind** for the framework. Then in the same solution add a default blank UWP app. 
Check the reference path for the Universal Windows reference is the same for both projects
![image](https://user-images.githubusercontent.com/189547/38154730-94e8a2b0-346b-11e8-9fe0-b93182044093.png)
_Mouse over the value to see the full path._

If they're the same, in the WTS project remove the reference to **Microsoft.Xaml.Behaviors.Uwp.Managed** and try that.

If still no success, try slowly removing items from the WTS project until it's identical to the other one. (Or you could modify the blank one to match the WTS generated one.)

If we get to this stage then you should have two projects that are identical in all aspects apart from their names and projectIds. If one continues to fail it's going to be very hard to identify the actual issue.

Beyond that, I'd try repairing installed components to see if that addresses the issue. (At this point we're probably past identifying what the actual issue is and assuming it's down to a corrupt install of something and hoping a repair/reinstall will fix it.)

**Comment by FIVIL** [comment] 2018-03-31 00:43
@mrlacey this time when i created a blank, code behind app in WTS it worked fine, so i started to make it more reach so i added each component individually to see what components make error and whats are not.
at last i ended up with 31 project (some of them worked and some of them didnt)which i published them here
https://github.com/FIVIL/test
and here is a summery of the part that caused error:
1.Project type:
navigation pan: when i used navigation pan as project type then no matter the rest of the work the project doesnt work but things are fine with blank and pivot and tabs
2.farmework:
all of them works fine i created a blank app with all of them individually  one by one and all the apps run and worked fine
3.pages:
for this test i made a lot of pivot and tabs and added each of the pages one by one some of them worked and some of them didnt here is the list of the pages with didnt work
i.setting
ii.media player
iii.master/deatile
iv.image gallery
other pages worked fine :)
4.application lunching:
i tested each option and they worked fine
5.application life cycle:
setting storage  causes error and as suspend and resume automatically requires setting and storage so it causes propblem too but multiple views work fine
6.background work:
works fine
7.connected experiance:
works fine
8.user intraction:
live title and first run prompt cause error but toast notification and drag and drop work fine
and i didnt test the rest.
then after that i started to delete and reinstall and update (in general word playing) with Nuget packeges  but it didnt make any changes and the error for all the projects is still the same error that i postes here many times (now i have 31 project in one solution with 13 error and all of them is same error in different projects.
so i hope these information can help you addressing and solving this problem maybe in future updates.

**Comment by mrlacey** [comment] 2018-04-01 18:51
@FIVIL the repository you linked to was empty but the information you provided has helped narrow things down a bit.
The commonality between the scenarios that don't work for you is that they all depend directly on Json.Net or on the community toolkit (which itself [depends](https://www.nuget.org/packages/Microsoft.Toolkit.Uwp/) on json.net)

The NetStandard version of Json.net does have some [framework dependencies](https://www.nuget.org/packages/Newtonsoft.Json/10.0.3) so these are now the most likely suspects.


To confirm this is the issue: Create an empty UWP app and add a reference to the json.net NuGet package. (You could also create a NetStandard app and add the reference to test that way too.)

To identify the dependency in question: enable verbose build output (see above) and hope that provides more specific details.

What I'd do next: Try repairing the Visual Studio installation. The only reason I know of for a framework dependency to not work (based on the screenshots you provided of the installation configuration above) is for the installation to not have completed correctly. This does sometimes happen and a repair should fix it.

**Comment by FIVIL** [comment] 2018-04-03 10:18
@mrlacey as you suspected the problem is with json.net, i created a blank UWP and added json.net nuget package and also .net stand library, as the result of adding json.net package both didnt run with the same error that i used to get from WTS, so json.net it is,
also i provided you with verbose  build result here below
[output.txt](https://github.com/Microsoft/WindowsTemplateStudio/files/1871096/output.txt)

**Comment by touseefbsb** [comment] 2018-04-03 10:43
finally its good news tht u guyx found out the problem, I had sort of same problem a while ago which was solved ofcourse , error was different but problem was also related to json stuff.

**Comment by crutkas** [comment] 2018-04-04 17:42
our unit test VMs should be stock VS which should catch this scenario.  right?

**Comment by mrlacey** [comment] 2018-04-05 13:53
@FIVIL unfortunatley, the detailed output doesn't provide any more information. Could you try

`install-package json.net -verbosity detailed` 

in the package manager console. This may help identify which framework has the issue. Alternatively just repair the whole VDS install.

@touseefbsb We haven't found the cause of the problem, any more than it's something that json.net depends on but appears to have been installed. 

@crutkas This seems to be an issue with a broken install of .Net framework components. I don't know how we'd test this and don't really think we should.

**Comment by FIVIL** [comment] 2018-04-05 18:11
@mrlacey  well, im getting this while running the command:
_________________________________________________________________________________________
PM> install-package json.net -verbosity detailed
Install-Package : A parameter cannot be found that matches parameter name 'verbosity'.
At line:1 char:26
+ install-package json.net -verbosity detailed
+                          ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Package], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 ________________________________________________________________
but also dont you think we have to address this issue  to newtonsoft team about their package, so they can identify what might be wrong??

**Comment by mrlacey** [comment] 2018-04-07 15:02
@FIVIL  yes, feel free to raise an issue with json.net as the issue is with one of their dependencies.
I believe you'll still be in the same position of trying to identify which framework has the issue and then fixing that.

My apologies on the above command. The verbosity parameter is only supported on th CLI, not the package manager.


I'm going to close this issue as it is not with WTS, it is a problem with a framework installation used as a dependency of an included library.
Feel free to let us know if you find a cause for this which is more than just a corrupt install.

I still believe reparing your VS install will be the quickest path to unblocking you.

**Closed by mrlacey** 2018-04-07 15:02 UTC
Labels: Not enough Information

**Comment by bolyb** [comment] 2019-01-18 14:33
For what it's worth, while in my case it was unrelated to WindowsTemplateStudio, I spent a significant amount of time trying to track down this same error message and this was the only useful thread anywhere I could find on the subject. The solution in my case ended up being that the reference to Microsoft.NETCore.UniversalWindowsPlatform NuGet package had somehow become missing from the project, which was strange because the project would still build without it as long as I didn't change the version number of an unrelated NuGet package. 

Hope this helps someone else in the same situation in the future!

**Comment by ZodmanPerth** [comment] 2019-07-30 01:54
In case it helps anyone coming here searching for ideas on how to resolve this error message (like I did), here's my story.

**Cause**

Renamed a UWP Test project, and the error started happening on that project.

**Fix**
* Changed the `Assembly name` of the project to align with the new project name
* Changed `InternalsVisibleTo` on a (Portable) project it depended on to align with the new project name
* Compiled

One or both of those things I changed fixed the issue.

**Comment by ZodmanPerth** [comment] 2019-07-30 02:27
I had further issues to the above.  In the `GlobalSection(ExtensibilityGlobals) = postSolution` section of my solution file, the order of elements had been changed.

I restored them back to the folowing order to get things working again:
* `SolutionGuid`
* `RESX_MoveToResources`
* `RESX_CodeReferences`

**Comment by donaldnp** [comment] 2019-10-15 02:06
I also ran into this with a different solution (after getting clues from this thread)...

I came back to a project after a while, and had literally changed nothing but it was no longer working, and had this error message. After reading a reference to nugets in this thread, I checked mine, and found there was an update waiting for Microsoft.NETcore.UniversalWindowsPlatform. When I updated that (from 6.2.8 to 6.2.9) it started working again.
