### ISSUE TITLE
Missing ImageGallery page icon and descriptions

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1232] opened 2017-10-04 14:03 UTC
Missing ImageGallery page icon and descriptions

**Comment by ralarcon** [comment] 2017-10-05 07:05
@crutkas are you going to create the icon and the descriptions? If not, let me know and we can take care.

**Comment by crutkas** [comment] 2017-10-06 21:17
I want this page reviewed by design team and a few others before we fully ship it.  I don't think we have time for 1.4 to be inclusive here

**Comment by ralarcon** [comment] 2017-10-09 08:00
Ok, by now, we will include the image gallery for "final" testing purposes but we will not ship it (making it unavailable). You can request the review. We finally ready, we can update the templates to include again and ship an update.

**Comment by mvegaca** [comment] 2017-10-10 13:54
Make as hidden on #1274

**Comment by dgomezc** [comment] 2017-10-19 09:59
@crutkas for the gallery page icon we can use this:

![image](https://user-images.githubusercontent.com/12777039/31765406-8be6916c-b4c4-11e7-9959-52dbe0161bd2.png)

It has been created by http://modernuiicons.com and is licensed CC. The camera icon was created from this source as well.

**Comment by crutkas** [comment] 2017-10-19 20:07
can we make this smaller?  very dominate

**Comment by crutkas** [comment] 2017-10-19 20:07
we also need to attribute back to them.

**Comment by ralarcon** [comment] 2017-12-05 11:42
Released in 1.5

**Closed by ralarcon** 2017-12-05 11:42 UTC
Labels: Page
