### ISSUE TITLE
Theme selection stops working when Frame navigates

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1175] opened 2017-09-21 09:48 UTC
### Repro steps

Open [BugRepro App](https://github.com/Microsoft/WindowsTemplateStudio/files/1320689/BugRepro.zip)
Go to Settings Page.
Set Dark Theme
Go to Page1
Click on Navigate Button

### Expected Behavior

Navigate to Page 2 and Page 2 is on dark theme.

### Actual Behavior

Navigate to Page 2 and Page 2 is on light theme.

**Comment by mrlacey** [comment] 2017-09-21 10:18
> Open BugRepro App

That's not an adequate repro step. What is that app? How was it created?
It will need to be recreated for other frameworks & language to test that the issue exists and if necessary is corrected there too.

**Comment by mvegaca** [comment] 2017-09-21 10:22
I've create this app using tab project with MVVM Basic and C#. Added two blank pages and settings page. Blank 2 removed from pivot. Button added in Blank 1 to navigate from Blank 1 to Blank 2.

**Comment by ralarcon** [comment] 2017-09-22 13:41
Agree with @mrlacey. The repro steps must define all the steps required to reproduce the issue from scrach.

**Comment by mvegaca** [comment] 2017-09-29 06:53
Is like if the second navigated frame only applies selected framework to title TextBlock but the page background always take the RequestedTheme (App.xaml) color.

**Comment by ralarcon** [comment] 2017-10-04 08:37
Moving to 1.5 as it is not urgent.

**Comment by mrlacey** [comment] 2017-10-04 11:43
Moving back to m1.4 Bugs in the generated code should be considered high priority.

**Comment by ralarcon** [comment] 2017-10-04 13:54
Yes, you are right. We postponed it because of it is not a bug directly in the generated code, you need to make some changes / modifications to get a direct repro, in this case, you need to navigate out of the main frame to be able to get a repro. Anyway, we can keep it and if we are able, we'll do.

**Comment by mrlacey** [comment] 2017-10-04 19:22
While the bug doesn't occur when using the generated code it occurs because of it in a perfectly valid use case. The NavigationService code is causing the bug because it's being used in the way it was supposed to.

**Comment by mvegaca** [comment] 2017-10-09 14:32
Fixed on PR #1255

The problem was that we are not setting the ThemeResource background to pages and when the color changes and navigate the background does not apply theme background

**Comment by sibille** [comment] 2017-10-11 11:23
Verified in dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.2

**Closed by sibille** 2017-10-11 11:23 UTC
Labels: bug, Can Close Out Soon, Generated Code
