### ISSUE TITLE
Right click menu not dismissing

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#728] opened 2017-07-11 18:06 UTC
I'm wondering if this is a repercussion of the icon addition.  In the screenshot, note the double context menu.

To repro: hover over the WTS menu item then hover over a different one.

![image](https://user-images.githubusercontent.com/1462282/28082924-aee305fa-6628-11e7-97da-a808d77d59a7.png)

i'm punting to 1.3 right now as i view this is a low priority

**Comment by sibille** [comment] 2017-07-12 10:59
This is caused by the hidden menu we included to show the icon. I did a test to remove this, and now the menu is dismissing correctly. I liked the house icon, but it's causing collateral effects. 
Maybe we should undo the hidden menu command and remove the WTS icon?
I'll prepare a pull request so you can have a look and choose ;-)

**Comment by crutkas** [comment] 2017-07-13 17:44
Can this be closed out?  Looks like we did a merge

**Comment by ralarcon** [comment] 2017-07-13 18:48
Yes. It is fixed by removing the trick to show the Icon

**Closed** 2017-07-13 20:08 UTC
Labels: Right Click, Wizard
