### ISSUE TITLE
New empty project crashes if I extend the ResourceDictionary in App.xaml

### ISSUE THREAD

**Issue by tomzorz** [Microsoft/WindowsTemplateStudio#414] opened 2017-05-28 16:47 UTC
If I create a new project (everything default, Blank starting page, only MVVMLight added) the app will crash on launch after I add anything to the ResourceDictionary in App.xaml.

![image](https://cloud.githubusercontent.com/assets/6363312/26530420/be799c0c-43d4-11e7-99c6-5951cf8ac426.png)

The only thing I change after project creation:

![image](https://cloud.githubusercontent.com/assets/6363312/26530446/fe219cc4-43d4-11e7-985d-635c7a0df559.png)

The launch/activation process gets this far, but fails at the point where the code references the NavigationService.

![image](https://cloud.githubusercontent.com/assets/6363312/26530459/42b868a4-43d5-11e7-9bd0-df98a0482eaf.png)

It seems like that adding any item to the ResourceDictionary will cause the ViewModelLocator constructor run _after_ we're trying to use it. (And the constructor is what's setting the ServiceLocator, see ViewModelLocator.cs:16)

This is as far as I got. At the moment this feels like a race condition, but it's completely possible that I'm missing something obvious 😄

**Comment by mrlacey** [comment] 2017-05-28 18:31
@tomzorz I'm unable to reproduce this using:
VS 2017 v15.3 ()
WTS Wizard version 1.0.17142.1
WTS Templates version 1.0.17142.1
with X86 & x64 compilation running on my desktop PC.

Can you confirm the versions of tooling you're using and what you're running on?

Are you also able to confirm that a breakpoint in the ViewModelLocato constructor isn't hit when you add the extra resource?

**Comment by tomzorz** [comment] 2017-05-28 18:45
VS 2017 v15.2
WTS 1.0.17142.1
Win10 15063.296

I can confirm that the VML constructor is _not_ being hit.

Tested both on x86 and x64. (And now also in release mode just to be sure.)

**Comment by mrlacey** [comment] 2017-05-28 19:38
> I can confirm that the VML constructor is not being hit.

Is that both with and without your extra resource?

I can't repro on 15.2 either.

Does the same thing happen to you if you create a project without WTS and add a new resource?

Does it also happen if you use the MVVMBasic framework?

Can you zip up and share the project where this is happening? So I can see if there's a difference in the code I have. If not it must be something local to you. 
I understand why you'd think it a possible race condition but from the code, I don't understand how that's possible. The ViewModelLocator *should* be created before there's any reference to the ActivationService.

**Comment by mbcrump** [comment] 2017-05-28 20:12
I was able to reproduce using : 

VS 2017 v15.2
WTS 1.0.17142.1
Win10 15063.296

My project https://1drv.ms/u/s!Av6Gusjj-XsJiepLM0KrQ5rElKc85A

**Comment by mrlacey** [comment] 2017-05-28 21:44
Repro steps:
Project Type = Blank (original instructions said "default" which is NavPanel)
Framework = MVVM Light

**Comment by tomzorz** [comment] 2017-05-28 21:51
@mrlacey sorry, I should've been more clear: Blank project type + MVVMLight (That's what I meant by blank page...)

**Comment by mrlacey** [comment] 2017-05-28 22:45
Ok. Here's what's happening with the generated code.
- App.OnLaunched assumes the navigation service will have already been created
- The Navigation Service is (should be) instantiated by the ViewModelLocator
- The ViewModelLocator is first instantiated when a page has been created.
- A page has not normally been already created when the app is launched (blank & Pivot) except for NavPanel apps as this creates a new ShellPage when setting up the ActivationService and the creation of that page triggers the creation of the VML.

Why does the error only occur when adding another resource? If the above is true then it should happen all the time.
I don't know why this occurs this way given these circumstances. *Something* is affecting when `XamlTypeInfo.GetXamlType` is being called. This method is called by the platform and deeper into the plumbing of app activation than I know. Deep technical knowledge of this area is needed from an expert.

Please note that this also affects 'Pivot & Tabs' apps too. Not just the 'Blank' project type.

**WORKAROUND** - works for Blank and Pivot project types
Change `OnLaunched` in App.xaml.cs to be like this

        protected override async void OnLaunched(LaunchActivatedEventArgs e)
        {
            if (!e.PrelaunchActivated)
            {
                var workaround = this.Resources["Locator"];  // Add this line
                
                await ActivationService.ActivateAsync(e); 
            }
        }

It seems we can't guarantee when the resources in App.xaml will have been instantiated and so we must code to allow for it. That *feels* like a potential platform bug (would want to investigate more before raising though - unless @crutkas  or @mbcrump know someone to talk to about this.)

Need to have a think about the best proper solution.
Some initial ideas:
- Add a good reason to access the VML before App.OnLaunch. Even if it's just calling a new `EnsureInitialized` method.
- Change the ActivationService constructor to instantiate the VML if `shell == null`
- Have ActivationService.ActivateAsync assign a NavigationService if null
- Give NavigationService a valid fallback (from VML) if accessed and null.
- Pass the NavigationService to ActivateAsync
- Separate IOC registration from VML creation and call from App constructor. Not the MVVM Light way though.
- Add something to App.xaml that forces the creation of the VML.
More suggestions/preferences welcome.

Things we also need to consider:
- Any impacts when we allow changing and renaming the start page (#100)
- How to change testing to avoid things like this in future?
- Is there anything else similar to this we may have missed?

**Comment by crutkas** [comment] 2017-05-28 23:03
I have a bunch of notes from the airplane trip on this.  Will file when I get to a more Static location with internet :)

**Comment by tomzorz** [comment] 2017-05-29 00:01
Great investigating @mrlacey 👍 

> Why does the error only occur when adding another resource? If the above is true then it should happen all the time.
> I don't know why this occurs this way given these circumstances. 

I'm leaning towards your assumption, but I didn't really want to open with that: this smells like a platform issue. Adding anything to that ResourceDictionary should be without its side-effects. (I mean we could increase loading times, but the order in which the code runs should stay the same.)

**Comment by mvegaca** [comment] 2017-08-24 14:16
I've done some fixes on ViewModelLocator initialization in relation with  Issue #968 
Those changes should fix this problem.

**Comment by crutkas** [comment] 2017-08-30 17:05
@mvegaca, can you test / verify / close this out?

**Comment by mvegaca** [comment] 2017-08-31 13:56
Fix checked on
Wizard: 0.14.17243.65005
Templates: 0.14.17243.13

**Closed by mvegaca** 2017-08-31 13:56 UTC
Labels: bug, Can Close Out Soon, MVVMLight
