### ISSUE TITLE
New project using MVVM has no references

### ISSUE THREAD

**Issue by hchattaway** [Microsoft/WindowsTemplateStudio#2634] opened 2018-10-08 20:37 UTC
I just did a fresh install of VS 2017 Ent...
I installed the Windows Templates
I created a new project using them and selected to use MVVM light along with a 1:many page.
Project was created, but upon compiling, it threw over 100 errors.. seems to be mostly for MVVM light...
in the references section, there are no references to the GalaSoft libs and trying to install them via the package manager didn't add them either.

I expected all references to have been added via the wizard.

VS 2017 ENT: 15.8.6
WTS version: 2.4.18260.1
Windows 10

any ideas why the references wouldn't have been added?  I would hope the wizard would create a runable project!

Thanks
Harold

**Comment by sibille** [comment] 2018-10-09 07:54
Hi Harold, 
thanks for reporting!
The wizard should generate a runnable project, with the Mvvmlight nuget added. All nugets should get restored too, if you have an internet connection. 
I just tested with the production version, and it works fine for me.
Did you see any errors in the Windows Template Studio Output window or in the log file (at C:\ProgramData\WindowsTemplateStudio\Logs)? Could you attach the logs/errors and the generated project? This would be helpful to diagnose what happened.

**Comment by mrlacey** [comment] 2018-10-09 09:56
@hchattaway also, if you've just reinstalled everything, can you confirm that you can create a blank UWP app and add the MVVMLight references manually

**Comment by sibille** [comment] 2018-10-19 07:32
@hchattaway, could you provide logs or reproduction steps?

**Comment by crutkas** [comment] 2018-11-05 11:17
@hchattaway I'm closing this, please reopen if you can provide more info as we can't reproduce this.

**Closed by crutkas** 2018-11-05 11:17 UTC
Labels: Not enough Information, bug
