### ISSUE TITLE
Our min version is November Update, not Anniversary update

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#416] opened 2017-05-29 04:36 UTC
Should be 14393

I tested 
Basic->MVVM light
Basic->Code behind 
Navpane->mvvm light

**Comment by mrlacey** [comment] 2017-05-29 08:21
*should* X-Ref #334 😉 

@sibille specifically [changed this](https://github.com/Microsoft/WindowsTemplateStudio/commit/f5fa1fdba1d6937de6621b928b8d3fd49596f45c) as part of something else but no explanation why.

**Comment by ralarcon** [comment] 2017-05-29 08:33
If we set the target platform min version to 14393 then, we will be forcing the users to have the SDK installed (when in fact it is not required) due to a "bug" in the sdk that requires the RS1 SDK to be installed when TPMinV=RS1 (this does not happen for any other target platform min version). 

We currently use the default configuration for file->new project that establish the following configuration by default:
![image](https://cloud.githubusercontent.com/assets/2638875/26542420/0f66a684-445a-11e7-9264-a40e7a39970d.png)

If finally, we will be asking the users for the target platforms this will become a parameter in the generation.

**Comment by crutkas** [comment] 2017-06-05 22:58
we are not in the business of supporting older versions.  Th1 is not our min.

Is there a tracking bug against VS/Windows on this?

**Comment by rido-min** [comment] 2017-06-07 00:29
This is by design, not a bug. If you select TPMinV=14393 VS will ask you to install the SDK.

**Comment by mrlacey** [comment] 2017-10-04 17:32
Closing this as we prepare to support FCU and are also changing the minimum supported target to CU with the 1.4 release

**Closed by mrlacey** 2017-10-04 17:32 UTC
