### ISSUE TITLE
Add a prerequisit for TemplateEngine to VSIX to ensure availablity of TemplateEngine

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1549] opened 2017-12-13 14:30 UTC
We no longer distribute the Template Engine dlls and should add a prerequisit for Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.TemplateEngine to the VSIX to ensure it is installed.

**Comment by mrlacey** [comment] 2017-12-13 15:45
Any way we can find out how likely it is this is already installed?
And do we have analytics recording this (or any other requirements) not already being on the machine? (If it's even possible to know this.)

**Comment by crutkas** [comment] 2017-12-13 19:15
what would make this not installed?  If it is a prerequisite and is not installed, what would someone need to do?

**Comment by sibille** [comment] 2017-12-14 08:07
Template Engine is shipped with Visual Studio Version 15.3 (https://github.com/dotnet/templating/wiki/Shipped-Engine-Versions) but we saw some exceptions in Telemetry where Template Engine dlls could not be resolved. Talking to the template engine team they indicated us that adding a prerequisit for Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.TemplateEngine should solve this problem. 
It's not a frequent problem and can be solved adding the Web workload or the .NET Core workload as those two trigger the inclusion of template engine.

**Comment by crutkas** [comment] 2017-12-15 02:12
ok.  So if that isn't in, what happens, it auto resolves and gets it or does the user have to do something?

**Comment by ralarcon** [comment] 2017-12-15 09:15
I think that having the pre-requisite will automatically install it if missing, but I will test it.

**Comment by ralarcon** [comment] 2017-12-15 17:39
I made a couple of tests:
- Installed VS with only UWP Workload.
- Installing and running WTS extension with only UWP workload installed does have the TemplateEngine present, no errors appear.
- Uninstalled VS Community.
- Installed VS Pro with just desktop development present.
- Installing VS with just desktop development workload and then our extension Installing our extension -- Installing and running WTS vsix works fine as well (our extension Install UWP workload as pre-requisite)

I will try to install VS and WTS in clean machine to try to reproduce the exceptions shown but, anyway, we will include the "Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.TemplateEngine" as pre-requiste for our VSIX.

**Comment by ralarcon** [comment] 2017-12-18 14:59
I tried again over a clean machine just with VS 15.5.2 installed. No workloads selected on the first VS install. 

After the VS installation, I've installed Windows Template Studio from the marketplace. The WTS installations depends on UWP workload which has been installed as a pre-requistite. Once finished, I launched WTS and generated a project with several pages with success (the Template Engine libraries were available).

Considering nobody has complained about this, I will not update the dependencies on our VSIX as I didn't being able to reproduce the error condition.

I will continue investigating to ensure the "language" is not an issue (as all the errors we have are from non-english languages).

**Comment by ralarcon** [comment] 2017-12-19 12:27
Tried again with a machine using **French** lang and without any VS workload installed. 
* Ensured the TemplateEngine is not present before installing WTS Vsix. 
* Installed WTS from the Visual Studio Marketplace (from VS).
* TemplateEngine now appears in the extensions folder.
* VS configured in French lang.
* Everything works as expected.

Closing the issue as I'm not able to reproduce it and the TemplateEngine dependency is being installed as part of our other dependencies (UWP Platform SDK).

**Closed by ralarcon** 2017-12-19 12:27 UTC
Labels: in-progress
