### ISSUE TITLE
Can't find the "Windows Template Studio" Project template after installing the dev nightly vsix

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsTemplateStudio#3987] opened 2020-12-07 12:25 UTC
**Describe the bug**
I don't see the option of Windows Template Studio project template after I install the dev nightly extension. I followed the steps and have installed the extension version 0.22.20337.1 as mentioned in the [WinUI Docs](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WinUI/readme.md)

**To Reproduce**
1. Install visual studio 2019 preview 
2. Install WinUI 3 preview 3
3. Install Windows Template VSIX from Dev nightly
2. Open visual studio and try to create new project
3. Search for windows template studio
4. No options

**Expected behavior**
See WTS project option

**Screenshots**
Can't attach from work laptop

**Additional context**
Trying to build a WinUI 3 app

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
|  |  | Yes |

**System**

- **VS Version:** : Version 16.9.0 Preview 1.0
- **WinTS Extension:** 0.22.20337.1
- **Windows Build:** 1909

**Comment by mrlacey** [comment] 2020-12-07 13:49
It was there with version 0.22.20322.1

![image](https://user-images.githubusercontent.com/189547/101357729-bd2a2000-3891-11eb-8a9b-f93972a09c0f.png)

I have updated to the latest build (0.22.20337.1) and it's still there:

![image](https://user-images.githubusercontent.com/189547/101358382-ac2dde80-3892-11eb-90c3-643d8304ae83.png)

Do you see any Windows Template Studio options? (Or is it just the WinUI ones that are missing?)

Double check your extension settings:
![image](https://user-images.githubusercontent.com/189547/101358537-e6977b80-3892-11eb-9ca9-68a2a5f0eb3b.png)

**Comment by harvinders** [comment] 2020-12-08 12:19
@mrlacey I do see winui 3 project options but not the WTS. I will try to reinstall the visual studio etc and see how that goes.

And yes, I have followed the instructions and installed as per them and your last screenshots.

**Comment by mrlacey** [comment] 2020-12-08 12:40
Do you see the UWP & WPF WinTS options?

**Comment by harvinders** [comment] 2020-12-08 12:52
I just reinstalled everything and here is an update

If I search "Windows Template Studio" I don't see any WTS project options, however if the search box is empty and I scroll to the bottom, I do see there are 4 WTS templates. 

@mrlacey Would you mind confirming that it is the search issue?

**Comment by mrlacey** [comment] 2020-12-08 13:31
I have the release and nightly versions installed.
But search only finds entries form the "proper" extension.
![create project search results](https://user-images.githubusercontent.com/189547/101489696-36d91100-3959-11eb-88f3-262308611a2b.png)

but if I scroll down I see the WinUI version

![scrolled down list of project templates showing the WinUI option](https://user-images.githubusercontent.com/189547/101489726-422c3c80-3959-11eb-99eb-e22d5c22271b.png)

In general I've found search to be very hit-and-miss when it comes to finding entries. I instead use the drop downs to filter the list and then scroll.

**Comment by sibille** [comment] 2021-04-27 05:20
Closing as duplicate of #4173

**Closed by sibille** 2021-04-27 05:20 UTC
Labels: WinUI3, bug
