### ISSUE TITLE
Template Studio is unable to create an app with whitespaces or hyphen in AppName

### ISSUE THREAD

**Issue by debjyotigorai** [Microsoft/WindowsTemplateStudio#2892] opened 2019-02-03 15:08 UTC
I am getting the following error while creating an UWP app in C# using MVVW Basic. I think the error is related to "Setting Storage".
## Error
System.Exception: Error executing 'Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction'. Related template: wts.Feat.SettingsStorage. ---> System.IO.FileNotFoundException: There is no merge target for file 'C:\Users\Debjyoti Gorai\source\repos\DG DEV (UWP)\DG_DEV__UWP_\Strings\en-us\Resources_postaction.resw'. Related Template: 'wts.Feat.SettingsStorage'.
   at Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction.HandleFileNotFound(String originalFilePath, String suffix)
   at Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction.ExecuteInternal()
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   --- End of inner exception stack trace ---
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   at Microsoft.Templates.Core.Gen.GenController.ExecutePostActions(GenInfo genInfo, TemplateCreationResult generationResult)
   at Microsoft.Templates.Core.Gen.GenController.<GenerateItemsAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.Core.Gen.NewProjectGenController.<UnsafeGenerateProjectAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.Services.GenerationService.<GenerateProjectAsync>d__5.MoveNext()

**Comment by crutkas** [comment] 2019-02-03 15:11
Possible to share the exact items you selected  outside of MVVM Basic?

I do agree it seems like a resource file for setting storage is missing.

**Comment by mrlacey** [comment] 2019-02-03 16:18
The issue is the space in the project name.

Simpler repro:

- Project name includes a space (e.g "with space")
- Navigation Pane
- MVVM Basic
- No extra pages
- No extra features

**Comment by crutkas** [comment] 2019-02-03 16:44
Thanks Matt for the quick triage and workaround. Unit test + fix for 3.1 then.

**Comment by mrlacey** [comment] 2019-02-03 16:48
Will add a fix for this and commit separately so it can go in sooner.

X-Ref #1784 (Some project names cause generated apps to not work)

I propopse making that a higher priority. We should do a better job of handling different input.

**Comment by crutkas** [comment] 2019-02-03 16:50
I thought we grabbed the VS code for file names. Maybe the logic needs to be diff for solution/project naming.

**Comment by mrgatesjunior** [comment] 2019-02-03 17:11
I am also getting this error and I believe it is due to a "-" in the project main name.  I will check it without the dash and report back.

**Comment by debjyotigorai** [comment] 2019-02-03 17:13
Now it working. Thanks for the workaround. It should warn the users of choosing a invalid project name and it's workaround before the wizard start creating the project.

**Comment by mrgatesjunior** [comment] 2019-02-03 17:13
Here is the output of the main issue:

System.Exception: Error executing 'Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction'. Related template: wts.Feat.SettingsStorage.VB. ---> System.IO.FileNotFoundException: There is no merge target for file 'C:\Users\jesse\source\repos\TNO-Crypt\TNO_Crypt\Strings\en-us\Resources_postaction.resw'. Related Template: 'wts.Feat.SettingsStorage.VB'.
   at Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction.HandleFileNotFound(String originalFilePath, String suffix)
   at Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction.ExecuteInternal()
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   --- End of inner exception stack trace ---
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   at Microsoft.Templates.Core.Gen.GenController.ExecutePostActions(GenInfo genInfo, TemplateCreationResult generationResult)
   at Microsoft.Templates.Core.Gen.GenController.<GenerateItemsAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.Core.Gen.NewProjectGenController.<UnsafeGenerateProjectAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.Services.GenerationService.<GenerateProjectAsync>d__5.MoveNext()

**Comment by mrgatesjunior** [comment] 2019-02-03 17:15
Yes, took the dash out and all seem to work fine.

**Comment by mrgatesjunior** [comment] 2019-02-03 17:17
BTW, it is not an invalid project name.  It is excepted across the board anywhere except with this extension, so in my opinion, needs to be resolved.

**Comment by debjyotigorai** [comment] 2019-02-03 17:19
>           BTW, it is not an invalid project name.  It is accepted across the board anywhere except with this extension, so in my opinion, needs to be resolved.

I know that. I have created project names with empty spaces, dashes, underlines etc. I think Template Studio doesn't support till yet.

**Comment by mrgatesjunior** [comment] 2019-02-03 17:20
Just referencing your comment of:

_Now it is working. Thanks for the workaround. It should warn the users of choosing a invalid project name and it's workaround before the wizard start creating the project._

**Comment by crutkas** [comment] 2019-02-03 17:39
Great feedback, we are 100% fixing this issue :). Big decision is hotfix vs wait until next release.

**Comment by mrlacey** [comment] 2019-02-03 19:09
>           I am also getting this error and I believe it is due to a "-" in the project main name.  I will check it without the dash and report back.

Yes, hyphens cause issues too. A fix is coming.

**Comment by mrgatesjunior** [comment] 2019-02-03 20:10
Thank you all, appreciate it.  And yes, dash is technically a hyphen :-)

**Comment by mrgatesjunior** [comment] 2019-02-03 20:32
So, just curious, did the problem arise with this commit ?

7c185aedfac4b976f23eb1a1e01d8b5e4095aed9

**Comment by mrlacey** [comment] 2019-02-03 20:40
> So, just curious, did the problem arise with this commit ?

No the issue is much older. There are places where the project name is being used for the namespace without first making it safe.

The merge is, for example, comparing `My-App` (the project name) with `My_App` (the "safe" project name) and failing because they're not equal. It's not specifically about file paths.

**Comment by mrgatesjunior** [comment] 2019-02-03 20:49
Can you point me to the compare method / logic, just curios to see where you are referencing that from.  I know in the previous release to this latest one, I could have a hyphen in the name and it worked fine.

**Comment by mrgatesjunior** [comment] 2019-02-03 21:35
Thank you for this.  I would strictly follow what is allowed as a valid name within VS as a project name.  That is just my two cents.  I think one could get crazy with naming standards and conventions, but to me, the bottom line is whatever is allowed as a normal naming standard within VS is probably what you would want to follow.

**Comment by mrlacey** [comment] 2019-02-04 14:10
Deferring the UI warning change to #1784 (and moving that to the 3.1 milestone) so this can go in ASAP.

**Comment by mrgatesjunior** [comment] 2019-02-07 02:24
Thank you for working on this !

**Comment by sibille** [comment] 2019-02-07 13:28
Just released Hotfix for this. Updating the extension to version 3.0.19038.01 should fix this. 
Thanks again for reporting this!

**Closed by sibille** 2019-02-07 13:28 UTC
Labels: Can Close Out Soon, Generated Code, bug
