### ISSUE TITLE
update roadmap

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1593] opened 2017-12-19 21:57 UTC
Roadmap shows 1.3 plans when we are looking at 1.7 and 2.0

**Comment by mrlacey** [comment] 2017-12-22 11:43
I think it will be beneficial to look at the whole roadmap and milestone/release process as part of updating the roadmap document.

At the moment, the process seems very disorganized and unstructured.

Here's how it seems the release occurs (based on the last few milestone releases)
- A milestone/release number if defined with no deadline/due date.
- Issues are assigned to the milestone on a seemingly random basis.
- There is a rush of work on some items assigned to the milestone early in its existence.
- Work on items assigned to the milestone slows after a couple of weeks.
- Entirely new issues are created and assigned to the milestone and are worked on straight away.
- Some items are moved to a future milestone without warning or explanation.
- There's a rush of work on the remaining issues and then a release is made with very little time for testing.
- The next [minor] release has new issues assigned to it without any indication of why and so that release becomes a mix of assorted new issues and issues carried over from the last release. (Some issues end up getting carried over several milestones.)


There are a number of issues here that I believe could and should be improved by following these action points

- Set a deadline for each milestone/release. It can, of course, be adjusted if needed but without one there's less incentive to get work that is part of a release done. It also helps with wider planning goals and external visibility and expectations. Particularly when someone is waiting for a particular feature of bug fix.
Deadlines for further out releases can be less specific and are more likely to change but upcoming minor releases should be, as far as possible, fixed and accurate.
At the moment there is a planned major update (2.0) but there is no way to know when this might be coming, what it might contain, or how many minor updates may happen before it comes.
A deadline also makes it possible to assess how realistic it will be to complete the amount of work that can be performed as part of a release. Without a deadline, there's always room to add more issues. With a deadline, it makes it possible to
The alternative to not having a deadline is to strictly define a set of issues to be completed and then release when they are done and tested. This way of working means that new items can't be added to a release as doing so extends the deadline.
Yes, there's a balance to be found but making it up as you go along isn't the answer. Ideally, the goal should be to have a set of features/issues that can be confidently completed in the amount of time defined. Doing this requires a clear definition of what is required for each feature before it is assigned to a milestone--which is a separate conversation that needs to be had.

- Have a clear outline and grouping of work being done in a particular release. When individual issues are addressed in isolation it means that functionally or logically related items can be split up. Doing so can have a number of consequences. The total amount of time taken to implement the related issues increases as time is not lost in context switching. Also, and potentially more importantly, doing related items together avoids making a change for one item that will make it more difficult to also support a related item in the future.

- Have a clear plan for the prioritization of work. Why do some issues spend months waiting to be implemented and others are done very quickly? When should entirely new items be added to a milestone that's already in progress? What constitutes a major update? I'm not saying these things need to be rigorously documented and enforced, rather that my concern is that currently there is almost no evidence of consideration for these issues and that should change.

- Have a dedicated period of testing before a release is made public. Big new features and changes shouldn't become part of an official release without time for wider feedback and testing. Changes and new features shouldn't be rushed through on the day before a new version is released.

- Include major areas of new functionality and features on the roadmap. Show planning beyond the next release to give people confidence in the long-term future of the project/tool.

Without the above, it makes it harder to be an external contributor to the project. It also makes it hard to assess potential future use or dependence on the tool.


Anecdotally, the frequency of releases seems to have slowed and the amount included in a release seems to have decreased. These are potential warning signs of large underlying issues. The above may address some of these but it's also worth monitoring if not being caused by external issues.

**Comment by ralarcon** [comment] 2018-01-22 17:18
The roadmap is updated. Closing this now.

**Closed by ralarcon** 2018-01-22 17:18 UTC
Labels: meta
