### ISSUE TITLE
RSS Feed like Windows App Studio

### ISSUE THREAD

**Issue by SimoneRaspagni** [Microsoft/WindowsTemplateStudio#2612] opened 2018-09-29 07:42 UTC
## For new Features:
I think would be nice if in the next versions it was possible to add RSS feeds (like Windows App Studio with rss link) using MasterDetails template!

**Comment by crutkas** [comment] 2018-09-29 14:13
Would you like to take a stab?

**Comment by mrlacey** [comment] 2018-10-01 12:13
This looks like a duplicate of #2095

**Comment by crutkas** [comment] 2018-10-01 16:55
@mrlacey  agreed, marking as dup.  really wish github on a mobile device would be easier to do stuff like this :)

**Closed by crutkas** 2018-10-01 16:55 UTC
Labels: duplicate
