### ISSUE TITLE
Uno Platform plus MVVM framework template

### ISSUE THREAD

**Issue by Alex-Dobrynin** [microsoft/WindowsTemplateStudio#4053] opened 2021-02-04 17:45 UTC
Do you have in plans to add support for Uno Platform in couple with some popular MVVM framework?

**Comment by mrlacey** [comment] 2021-02-04 19:34
Closing as duplicate of this request: #2658 

Short answer: There's nothing planned yet but as more people ask for this it helps make the case.

**Closed by mrlacey** 2021-02-04 19:34 UTC
Labels: needs-triage
