### ISSUE TITLE
Navigation menu not completly visible after adding CommandBar

### ISSUE THREAD

**Issue by kastrupi** [Microsoft/WindowsTemplateStudio#1098] opened 2017-09-07 07:54 UTC
Hi,

I wanted to add a CommandBar to the Page.BottomAppBar. After doing so part of navigation menu is not visible. Unfortunately solution suggested in https://github.com/Microsoft/WindowsTemplateStudio/issues/425 won't work because CommandBar gets positioned at the bottom of all content and not at bottom of the page.

I tried adding CommandBar to the ShellPage:

   ```
<controls:HamburgerMenu
            x:Name="NavigationMenu"
            DisplayMode="{x:Bind ViewModel.DisplayMode, Mode=OneWay}"
            PaneBackground="{ThemeResource SystemControlBackgroundAltHighBrush}"
            IsPaneOpen="{x:Bind ViewModel.IsPaneOpen, Mode=TwoWay}"
            ItemTemplate="{StaticResource NavigationMenuItemDataTemplate}"
            ItemsSource="{x:Bind ViewModel.PrimaryItems}"
            OptionsItemTemplate="{StaticResource NavigationMenuItemDataTemplate}"
            OptionsItemsSource="{x:Bind ViewModel.SecondaryItems}"
            Style="{StaticResource FallCreatorsUpdateHamburgerMenuStyle}"
            >
        <i:Interaction.Behaviors>
            <ic:EventTriggerBehavior EventName="ItemClick">
                <ic:InvokeCommandAction Command="{x:Bind ViewModel.ItemSelectedCommand}" />
            </ic:EventTriggerBehavior>
            <ic:EventTriggerBehavior EventName="OptionsItemClick">
                <ic:InvokeCommandAction Command="{x:Bind ViewModel.ItemSelectedCommand}" />
            </ic:EventTriggerBehavior>
        </i:Interaction.Behaviors>
        <Grid Background="{ThemeResource SystemControlBackgroundAltHighBrush}">
            <Frame x:Name="shellFrame"/>
            <CommandBar VerticalAlignment="Bottom">
                <AppBarButton Icon="Add" Label="Add"/>
                <AppBarButton Icon="Bullets" Label="Select" x:Name="SelectButton"/>
                <AppBarButton Icon="Delete" Label="Delete" Visibility="Collapsed"/>
            </CommandBar>
        </Grid>
        <VisualStateManager.VisualStateGroups>
            <VisualStateGroup x:Name="WindowStates">
                <i:Interaction.Behaviors>
                    <ic:EventTriggerBehavior EventName="CurrentStateChanged">
                        <ic:InvokeCommandAction Command="{x:Bind ViewModel.StateChangedCommand}"/>
                    </ic:EventTriggerBehavior>
                </i:Interaction.Behaviors>
                <VisualState x:Name="PanoramicState">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="1024"/>
                    </VisualState.StateTriggers>
                </VisualState>
                <VisualState x:Name="WideState">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="640"/>
                    </VisualState.StateTriggers>
                </VisualState>
                <VisualState x:Name="NarrowState">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="0"/>
                    </VisualState.StateTriggers>
                </VisualState>
            </VisualStateGroup>
        </VisualStateManager.VisualStateGroups>
    </controls:HamburgerMenu>
```
	
This approach makes navigation menu visible, but have one big downside. CommandBar is tied to the ShellViewModel and not to a specific page ViewModel.

How can this be fixed?

VS Version: Microsoft Visual Studio Community 2017 Version 15.3.3
WTS Wizard Version: 1.2.17198.1
WTS Template Version: 1.2.17202.1
Windows Build: Windows 10 Pro 10.0.15063

**Comment by mvegaca** [comment] 2017-09-07 09:42
We currently don't have and implementation or solution to add a command bar. We can think about adding a new feature to add command bar in the project where different pages can add commands to command bar.
By now, maybe a simple aproach you could try is to pass commands from specific view models to shell viewmodel and update shell command bar commands.

**Comment by mrlacey** [comment] 2017-09-07 11:58
@kastrupi if you add the command bar to the shell but want to access it from individual pages there are a few options.
- Make the ShellViewModel static so you can access it from any page
- Pass a reference to the ShellViewModel instance to each individual page
- Have the ShellViewModel forward actions based on the command bar items to the VM of whichever page instance is currently shown.

If you want to have different items on the command bar for different pages then having the bar on each page might be simpler.

Unfortunately, there's no one best way to deal with this and how command bars are used in combination with other navigation elements (like the HamburgerMenu) can vary greatly depending on the requirements of individual apps. This makes it something we can't easily build into templates.

I've updated the details on #425 (request for documentation on adding CommandBars) to cover the extra permutations brought up here. Hopefully, once these have been written they will make things clearer and avoid others running into issues in the future.

**Comment by mvegaca** [comment] 2017-09-11 08:45
Could we close this issue in favor of issue #1099? Feature: Application CommandBar

**Comment by mrlacey** [comment] 2017-09-15 10:09
Closing as a dupe of #425 which added documentation to explain the reason for this issue and how to work around it.

**Closed by mrlacey** 2017-09-15 10:09 UTC
Labels: Documentation
