### ISSUE TITLE
any type of icons in navigation menu

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#436] opened 2017-06-07 11:03 UTC
navigation menu currently accepts Symbol Icons it should be in general and icon so it could accept font Icon, or even third party icons like fontAwesome.UWP icons, in case the app needs different set of icons.

**Comment by skendrot** [comment] 2017-06-07 14:07
I believe the next version of the navigation menu template will use the UWP Community Toolkit which allows you to put anything for the menu items

**Comment by mrlacey** [comment] 2017-06-07 14:13
@skendrot sadly not. The WTS implementation still uses a VM which contains a `Symbol` property. There's nothing in the HamburgerMenu control that defines what should be in a menu item.

@touseefbsb the common ancestor of all of the types of "icon" you mention is `IIconElement` but then if we really want to be flexible isn't there an argument for making the menu items able to also show an Image, or any UIElement?  
I get that the current implementation is limiting but how far should we go at opening it up to other things?

**Comment by touseefbsb** [comment] 2017-06-07 14:15
I agree with you, if we can show any type of UI element there it would be even more flexible :)

**Comment by mrlacey** [comment] 2017-06-07 14:26
Having *any* kind of content there would add complexity to the code or generalize it undesirable ways and so not serve the goal of being a simple starting point. I don't like the idea of making the property in the VM a `FrameworkElement` or adding converters for different Icon types either. I'm not sure it would make it clear how to extend things or serve as a particularly good example. - I haven't dug into the full details of such a change. This is just a gut feel and would be happy to be wrong.

I suspect the best solution, for now, would be to add a document explaining how to change it and then look to make it a bit more flexible in a future version.
If you have anything to contribute to either of these (as I guess you're working on something that involves changing this at the moment) it would be appreciated.

**Comment by touseefbsb** [comment] 2017-06-07 14:42
I suggested this because I am working on a project which needs different type of icons ( which don't exist in UWP by default ) so I am using FontAwesome.UWP nugget library to add some icons, the look and feel of these icons can be slightly different then defauly uwp icons, hence if navigation menu has symbol icons and rest of the app includes third party icons, the experience would not be delightful for the user.
Again I am not sure about it because some icons doesn't make much different but some third party libraries provide icons which have relatively bolder font hence causing visual imbalance.

**Comment by crutkas** [comment] 2017-06-07 16:15
To unblock you @touseefbsb, why not just swap the fonticon out for whatever you need in ShellPage and update Symbol and SymbolAsChar in ShellNavigationItem to what you need?  Pretty quick and easy swap.  Our wizard has some more complex logic that detects XAML / SVG or a PNG and renders appropriately.

@mrlacey NavigationView in FCU's sample uses AppBarButton.  That uses IconElement.  Maybe we should swap out to AppBarButtons / IconElement

- https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview
- https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.appbarbutton

**Comment by mrlacey** [comment] 2017-06-07 17:42
@mvegaca as you were responsible for [changing to use SymbolIcon](https://github.com/Microsoft/WindowsTemplateStudio/commit/a0a20b7dc9be93b12401f8089a378f11b8458ea1) can you provide information on why this change was made and any potential consequences of moving back to something more generic?

**Comment by mrlacey** [comment] 2017-06-07 18:03
@crutkas got a link to the sample you mention?

**Comment by crutkas** [comment] 2017-06-07 19:32
@mrlacey sorry. Pasted wrong link

https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/navigationview#how-to-use-navigationview

**Comment by mrlacey** [comment] 2017-06-07 19:47
@crutkas that example uses AppBarButtons in the header, not in the menu. In the MenuItems is uses SymbolIcons assigned to a property that takes an IconElement. Can look to change to that based on what @mvegaca says.

**Comment by crutkas** [comment] 2017-06-07 21:24
@mrlacey sorry, you're correct, it uses a [NavigationMenuItem])https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationmenuitem) which still uses an IconElement

**Comment by mrlacey** [comment] 2017-06-28 16:11
What are the implications for doing this on #267 (Right-Click add)?

After we've done this and the new templates generate a ShellMenuItem that requires an `IconElement` rather than a `Symbol`?
Will the add new item always use the newest page/item/feature template? And is there anything a developer wanting to integrate can do if they built the project with the old style and the templates have now changed, apart from a manual merge?

This is just a simple example but I expect more of these type of issues going forward (all the changes for FCU are an obvious example.)  

Do we just primarily focus on the new project generation and treat adding anything as a bonus? Or, is there something we should do when changing a template (version related or otherwise) to help with adding to an existing project built with older versions of templates?

/cc @ralarcon

**Comment by crutkas** [comment] 2017-06-28 17:27
actually i tested this, not sure how they use iconelement as my attempts to put this in xaml don't seem to be functional.  interesting.

for right click add, i think we'd have a merge issue and it would be flagged.

**Comment by ralarcon** [comment] 2017-06-29 06:36
The most simple we can keep the right-click additionsthe better, but as you mention this would be an issue over time... the simplest way is to show a "merge conflict". Sometimes we can figure out to add some engineering to allow evolve without breaking changes (sometimes will be impossible). 

We can test and play with other approaches. In App Studio we were used to create a "version upgrader" when we introduce breaking changes, but this would be really difficult to be consistent. 

Other option to include versioning in projects and have different page and feature templates which work with certain project versions. That is, we can have concret version of the pages and features (i.e. "FCU Blank Page") which only will be selectable if the project have certain version. Then we can think in retire the old versions of pages and features when the usage decrease. With this approach, we can think in provide "version upgrade guidance" for users to "implement" by them self required actions to upgrade the project version (or try to do it automatically)...

**Comment by ralarcon** [comment] 2017-06-29 18:56
Thinking about this and sharing with @sibille we reach the following way to hold things properly... Breaking changes to templates must be hold within a new template, that is, if we are going use other improved staff for the Navigation pane project type, we will need to create another project type which uses the new features. Then we can have the same pages but using different post-actions to include in the new project type. 

With this approach, we will not require to hold versioning itself and the existing staff can continue working with the previous pages / features.

Anyway, we can always give guidance to our users to "upgrade" their projects...

**Comment by crutkas** [comment] 2017-06-29 19:03
works for me, i think this topic will need to be revisited for navigation view but that is a future problem

**Comment by mrlacey** [comment] 2017-06-29 20:27
Seems pretty doable. And without breaking backward compatibility too. 


![image](https://user-images.githubusercontent.com/189547/27708684-917f37a6-5d11-11e7-8c9b-9613ac2d89d0.png)

```
    _primaryItems.Add(ShellNavigationItem.FromType<BlankPage>("Shell_Blank".GetLocalized(), Symbol.Map));
    _primaryItems.Add(ShellNavigationItem.FromType<Blank1Page>("Shell_Blank1".GetLocalized(), new FontIcon { Glyph = "\uE128" }));
    _primaryItems.Add(ShellNavigationItem.FromType<Blank2Page>("Shell_Blank2".GetLocalized(), new FontIcon { Glyph = "\uE11D" }));
    _primaryItems.Add(ShellNavigationItem.FromType<Blank3Page>("Shell_Blank3".GetLocalized(), new PathIcon { Data = (Windows.UI.Xaml.Media.Geometry)Windows.UI.Xaml.Markup.XamlReader.Load("<Geometry xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'>F1 M 16,12 20,2L 20,16 1,16</Geometry>") }));
```

Just running tests and will raise PR tomorrow.

**Comment by crutkas** [comment] 2017-06-29 21:01
Any reason why we don't include default icons for our pages as well?

**Comment by mrlacey** [comment] 2017-06-30 07:42
@crutkas because there are no standard icons that apply to the abstract page types. We use generic icons for developers to change to whatever is appropriate to their app.  
Also adding `TODO` notes to these sections to make it clearer that the symbols should be changed once generated.

**Comment by mrlacey** [comment] 2017-06-30 17:54
I've done this so that everything we have already continues to work the same way but it's easy to change and use any IconElement descendant instead of a Symbol if so desired.

@ralarcon I'm concerned about this idea that breaking changes mean a new template. Doesn't that just mean more templates and duplication? How long do we support the "old" templates for? How do we define newer versions of a template? Can people still choose to use the old once a new one is released? How will the different post actions be selected? Have you tried implementing something like this yet?

**Comment by ralarcon** [comment] 2017-07-04 07:11
@mrlacey The idea behind creating a new template for breaking changes is to try to avoid complexity. We need to try to keep compatibility as much as possible. Then, if required to make a real breaking change, we need a way to allow people having old stuff to continue working with previous templates in the right-click but not necessarily in the "New Project". It means more templates and duplication but just for a while. This needs to be depth by making a PoC to check what is the best way.

**Comment by mrlacey** [comment] 2017-07-04 09:42
@ralarcon you say duplication will be less complexity but I worry it will be more. What have you done to verify the impact of this duplication? Surely adding the ability to handle multiple versions of templates will introduce a new level of complexity to the wizard and template management--or have you looked at what will be involved?
Why will duplication be " just for a while"? Is the intention that it will only be possible to add to existing projects if they were created within a specific recent time frame?

**Comment by mrlacey** [comment] 2017-07-05 16:17
Confirmed in DevNightly build with wizard version 0.14.17186.65008 and template version 0.14.17186.7

**Closed by mrlacey** 2017-07-05 16:17 UTC
Labels: Can Close Out Soon, enhancement

**Comment by cafuentealbam** [comment] 2017-10-03 18:44
you can use any font icon           

` _primaryItems.Add(new ShellNavigationItem("Shell_DondePagar".GetLocalized(), new FontIcon { Glyph = "\ue90b", FontFamily = new FontFamily("/Assets/Fonts/ModuloAutoconsulta.ttf#ModuloAutoconsulta") }, typeof(DondePagarViewModel).FullName));
`
