### ISSUE TITLE
WinUI 3 Templates - Unreachable code in NavigationService

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4033] opened 2021-01-14 18:30 UTC
**Describe the bug**
While I was working on Issue #4012 I've seen that there is some unreachable code in WinUI 3 NavigationService.

```csharp
        public Frame Frame
        {
            get
            {
                if (_frame == null)
                {
                    // This code is unreachable
                    _frame = Window.Current.Content as Frame;
                    RegisterFrameEvents();
                }

                return _frame;
            }

            set
            {
                UnregisterFrameEvents();
                _frame = value;
                RegisterFrameEvents();
            }
        }
```
We should fix it in dev branch.

**Comment by mrlacey** [comment] 2021-01-14 19:37
Is this a duplicate of #4032?

**Closed** 2021-01-15 07:52 UTC
Labels: WinUI3, bug, needs-triage

**Comment by mrlacey** [comment] 2021-01-15 10:09
why closed? was it a duplicate?

**Comment by mvegaca** [comment] 2021-01-15 13:54
Yes, I've closed it because it is duplicated :)
