### ISSUE TITLE
Icon improvement for "What's New Prompt"

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1052] opened 2017-09-01 03:09 UTC
Icon for "What's New" is not centered and unclear what the icon is supposed to be.  I'm supposing it is a ! 

![image](https://user-images.githubusercontent.com/1462282/29953816-1008ea7a-8e88-11e7-9780-b8aee533cd7a.png)

**Comment by crutkas** [comment] 2017-09-05 10:50
@mrlacey does this render weird for you?

**Comment by mrlacey** [comment] 2017-09-05 16:23
Yes, and a lot of the other icons look blurry to me too.
![image](https://user-images.githubusercontent.com/189547/30071499-d39105b6-925e-11e7-9fac-34fc58836756.png)

**Comment by crutkas** [comment] 2017-09-05 17:41
glad i'm not the only one that noticed that.  Ok, we should go in and fix this.

**Comment by mrlacey** [comment] 2017-09-13 13:08
assigning this a milestone as really should have been done as part of 1.3 but was probably overlooked as no milestone set.

**Comment by ralarcon** [comment] 2017-10-04 09:12
@crutkas are you taking care of this?

**Comment by mrlacey** [comment] 2017-10-04 13:35
I'll do it

**Comment by mrlacey** [comment] 2017-10-04 13:39
Now looks like this

![image](https://user-images.githubusercontent.com/189547/31178599-80f5fa5e-a911-11e7-8ca3-a6412424dd0b.png)

**Comment by ralarcon** [comment] 2017-10-04 13:56
Looks good!

**Comment by crutkas** [comment] 2017-10-04 16:02
What was causing he icons to look blurry

**Comment by mrlacey** [comment] 2017-10-06 13:16
Confirmed improvements in DevNightly

Wizard: 0.14.17278.65001
Templates: 0.14.17279.3

**Closed by mrlacey** 2017-10-06 13:16 UTC
Labels: Can Close Out Soon, enhancement, Wizard
