### ISSUE TITLE
Method not found on download

### ISSUE THREAD

**Issue by tomascw** [Microsoft/WindowsTemplateStudio#328] opened 2017-05-13 03:52 UTC
I get a method not found error when templates are about to download.

![](http://i.imgur.com/LXD5OUk.png)

**Comment by mrlacey** [comment] 2017-05-13 04:57
Can you provide any additional information to help identify the cause of this:
- Does it happen every time?
- What version of Visual Studio are you using?
- What version of the OS do you have?
- Have you tried reinstalling the VSIX?

**Comment by AustinWinstanley** [comment] 2017-05-13 06:04
I'm getting the same:

```
System.MissingMethodException: Method not found: 'System.Func`3<Microsoft.TemplateEngine.Abstractions.ITemplateInfo,System.String,System.Nullable`1<Microsoft.TemplateEngine.Edge.Template.MatchInfo>> Microsoft.TemplateEngine.Edge.Template.WellKnownSearchFilters.LanguageFilter(System.String)'.
   at Microsoft.Templates.Core.TemplatesRepository.GetAll()
   at Microsoft.Templates.UI.GenComposer.GetSupportedFx(String projectType)
   at Microsoft.Templates.UI.ViewModels.ProjectSetupViewModel.LoadFrameworks(MetadataInfoViewModel projectType, MetadataInfoViewModel orgFramework)
   at Microsoft.Templates.UI.ViewModels.ProjectSetupViewModel.set_SelectedProjectType(MetadataInfoViewModel value)
   at Microsoft.Templates.UI.ViewModels.ProjectSetupViewModel.<InitializeAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.Views.ProjectSetupView.<<-ctor>b__3_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Microsoft.Internal.VisualStudio.PlatformUI.WindowHelper.ShowModal(Window window, IntPtr parent)
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.ShowModal(Window dialog)
   at Microsoft.Templates.UI.GenController.GetUserSelection()
```

* Does it happen every time?
Yes

* What version of Visual Studio are you using?
    * Visual Studio Enterprise 2017
    * Visual Studio Enterprise 2017 15.3-Preview
    * Visual Studio Community 2017 15.3-Preview

* What version of the OS do you have?
Windows 10 Pro

* Do you have any versions of dotnet new installed?
    * **C:\\Program Files\\dotnet\\sdk\\**
        * 1.0.0
        * 1.0.2
        * 1.0.3
        * 1.0.4
        * 2.0.0-preview1-005977
    * **C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\**
        * 1.0.4
        * 1.0.5
        * 1.1.1
        * 1.1.2
        * 2.0.0-preview1-002111-00

* Have you tried reinstalling the VSIX?

Yes

**Comment by tomascw** [comment] 2017-05-13 14:39
* Does it happen every time? Yes.
* What version of Visual Studio are you using? 2017 and 2017 Preview
* What version of the OS do you have?  Creators Update 1703, 15063.296
* Do you have any versions of dotnet new installed? 1.0.0, 1.0.3, 1.0.4, 2.0.0-preview1-005977 / 1.0.1, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 2.0.0-preview1-002111-00
* Have you tried reinstalling the VSIX? Not that I recall

**Comment by crutkas** [comment] 2017-05-13 15:19
we saw something like this on preview the night before our session but couldn't repro on RTM.  I got the same stack trace.

100% issue, i'm going to say this is a 1.01 issue to stabilize but VS non-preview does work with that error.

**Comment by crutkas** [comment] 2017-05-16 01:25
Ok, i can repro this in preview with the VSIX but I cannot repro this in code.

**Comment by crutkas** [comment] 2017-05-16 02:11
I've compiled and installed locally, doesn't seem to have an issue.  I thought it may due to an outdated nuget to the template engine but the fact the dev branch won't cause this makes me wonder

**Comment by crutkas** [comment] 2017-05-16 02:20
Ok, release mode compile local VSIX confirmed to cause this.

**Comment by crutkas** [comment] 2017-05-16 02:36
Fix ready.  Updating the nuget reference to the VS template generator fixed this in #344

**Comment by mrlacey** [comment] 2017-05-16 19:14
@crutkas Why does updating the NuGet package fix this? Would be good to understand what the actual issue is and why it only affected some people. What's to stop this new version affecting a different set of people?

**Comment by crutkas** [comment] 2017-05-16 20:07
VS 15.3 Preview updated a reference and they have a bug where they weren't rev'ing the Assembly.  We referenced an older assembly and we exploded.  

https://github.com/dotnet/templating/issues/804

**Comment by mrlacey** [comment] 2017-05-16 22:19
Hmm. reported as affecting VS15.2 as well though. Hopefully a reporting error. A good argument for getting more (system) info added to the error dialog.

**Comment by crutkas** [comment] 2017-05-17 01:12
@mrlacey who reported this exact issue on 15.2?

**Comment by mrlacey** [comment] 2017-05-17 14:40
@crutkas it's in this thread above

> Ok, the first time it failed in VS 2017 15.2 Enterprise

**Comment by crutkas** [comment] 2017-05-17 16:49
@AustinWinstanley can you reach out to me.  the fact this happend on a 15.2 install worries me but every other report seems to be 15.3.

**Comment by crutkas** [comment] 2017-05-18 00:34
Fix is in production

**Closed by crutkas** 2017-05-18 00:34 UTC
Labels: bug, Can Close Out Soon, Ready to merge, VS Preview Issue, Wizard
