### ISSUE TITLE
build error in latest dev nightly build

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#471] opened 2017-06-17 11:51 UTC
I just updated to latest dev nightly build and the project is not compiling with following error on almost each page

Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.		

Meanwhile I have another project on the previous version of dev nightly build and that project is just building fine, and these 2 projects are in same solution.

**Comment by touseefbsb** [comment] 2017-06-17 12:20
solved this by installing nuget package manually 
Microsoft.NETCore.UniversalWindowsPlatform

**Comment by crutkas** [comment] 2017-06-17 15:20
What was the recipe you used

**Comment by touseefbsb** [comment] 2017-06-17 15:40
M sorry what do you mean by recepie

**Comment by crutkas** [comment] 2017-06-17 15:52
Options you used to create the project. (How I we reproduce what the error basically :))

**Comment by touseefbsb** [comment] 2017-06-17 15:55
I used a media player page, a tabbed page, 4 black pages, toast notification service, live tile service, and I created the project in .Net 4.7 but error was coming bcz I didnt have the universalplatform .net core package in my project which is the basic package, but I guess it might be a problem with my visual studio because it didnt install the missing package automatically at the first build.

**Comment by mrlacey** [comment] 2017-06-17 19:02
we're you offline when adding the new project? That was historically the cause of this issue but should be fixed in Dev Nightly.

I suspect the information to fully debug what happened is now lost because it would have been in the Windows Template Studio output window.

**Comment by touseefbsb** [comment] 2017-06-17 19:48
no I wasnt offline. I suspect this error also occurs due to problem in nuget package manager on VS on the developer machine,so that might be the cause before I updated my VS just before updating my template studio

**Comment by ralarcon** [comment] 2017-06-19 07:56
This error is related to the solution ability to restore the nuget packages. 

You should have a log file located at %programdata%\WindowsTemplateStudio\Logs. The most recent file should have information to be able investigate further.

**Comment by crutkas** [comment] 2017-06-19 17:52
@touseefbsb can you upload the logs?

**Comment by touseefbsb** [comment] 2017-06-19 21:27
Log files vanished after visual studio got updated but i guess it's ok bcz problem was in visual studio and not in wts

**Comment by touseefbsb** [comment] 2017-06-19 21:28
And it was solved after manual install of package

**Comment by crutkas** [comment] 2017-06-20 00:19
@touseefbsb it worries me when something doesn't work :)

Closing now but if anyone see it, lets reopen.

**Closed by crutkas** 2017-06-20 00:19 UTC

**Comment by touseefbsb** [comment] 2017-06-20 09:03
yes sure if anyone else has the same issue we can help them so we can reopen :)
