### ISSUE TITLE
Info prompt bar disappears too quickly at times

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#757] opened 2017-07-12 04:29 UTC
I can't repro this consistently but i've seen it multiple times.

**Repro steps that i've seen it occur:**
1. select framework and project type
1. click next
1. add page
1. click back
1. change framework

**expected:**
bar will appear and go away in ~5 seconds

**actual:**
bar flashes on the screen for a ~half a second

**Comment by crutkas** [comment] 2017-07-12 18:50
How i can get it to repro again and again:

follow repro steps (you don't actually need to add a page)

To cause it to occur again, fully exit WTS and restart your file->new experience

**Comment by mvegaca** [comment] 2017-08-28 13:54
Now I can reproduce it, I'm going to work on it.

**Comment by mvegaca** [comment] 2017-08-28 14:19
This occurs because when the template update process ends wizard status is cleaned and in this case, current status is an important warning.
Added a PR #1017 with current status can be cleaned validation.
Can you approve the PR @crutkas?

**Comment by crutkas** [comment] 2017-09-01 17:04
punt to 1.4

**Comment by mvegaca** [comment] 2017-10-05 08:46
Fixed on #1236

**Comment by mvegaca** [comment] 2017-10-05 14:41
Reopening

**Comment by crutkas** [comment] 2017-10-06 22:02
why did the fix seem like it worked but didn't?

**Comment by ralarcon** [comment] 2017-10-09 09:25
The fix is inplace but we didn't verified it yet with the nightly version... previously closed by error.

**Comment by sibille** [comment] 2017-10-10 09:05
Verified on dev-nightly:
Wizard: 0.14.17283.65001
Templates: 0.14.17283.1

**Closed by sibille** 2017-10-10 09:05 UTC
Labels: bug, Can Close Out Soon, Wizard
