### ISSUE TITLE
Appcenter throws System.InvalidOperationException

### ISSUE THREAD

**Issue by artkat** [microsoft/WindowsTemplateStudio#4178] opened 2021-03-29 15:33 UTC
When including the AppCenter functionality, either through the steps as described in AppCenter or by creating a new product using TemplateStudio with the inclusion of AppCenter, will result in the immediate silent exception of AppCenter "Exception thrown: 'System.InvalidOperationException' in Microsoft.AppCenter.dll"

**To Reproduce**
1. Start a new project selecting "Windows Template Studio (Universal Windows)
2. Select Features/VS App Center Analytics
3. Create Project
4. In app.xaml.cs, replace {Your App Secret} with the key provided by AppCenter.

**Expected behavior**
No exception.
Logging of app data in AppCenter protal.

**Comment by sibille** [comment] 2021-03-30 07:17
Thanks for reporting! We'll have a look at this.

**Comment by vmadurga** [comment] 2021-04-06 14:20
Hi @artkat, we couldn't reproduce the error. Can you provide us a sample repro project? (without including the AppCenter key)

**Comment by sibille** [comment] 2021-04-12 13:48
Moving to the backlog as this needs more information to be able to reproduce.

**Closed** 2021-04-23 00:00 UTC
Labels: Not enough Information, Status- No recent activity, bug, needs-author-feedback
