### ISSUE TITLE
Build dev.templates.tests.full_20180109.1 failed

### ISSUE THREAD

**Issue by wasteam** [Microsoft/WindowsTemplateStudio#1661] opened 2018-01-09 05:26 UTC
## Build dev.templates.tests.full_20180109.1
- **Build result:** `failed`
- **Build queued:** 1/9/2018 4:59:58 AM
- **Build duration:** 26.18 minutes
### Details
Build [dev.templates.tests.full_20180109.1](https://winappstudio.visualstudio.com/web/build.aspx?pcguid=a4ef43be-68ce-4195-a619-079b4d9834c2&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f24622) failed

+ xunit.console.exe :     GenerateAllPagesAndFeaturesAndCheckWithVBStyleAsync(projectType: "Blank", framework: 
"MVVMBasic") [FAIL]
At pbatch:27 char:27
+ 
    + CategoryInfo          : NotSpecified: (    GenerateAll...MBasic") [FAIL]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : [localhost]
 
    GenerateAllPagesAndFeaturesAndCheckWithVBStyleAsync(projectType: "Blank", framework: "MVVMLight") [FAIL]
    GenerateAllPagesAndFeaturesAndCheckWithVBStyleAsync(projectType: "Blank", framework: "CodeBehind") [FAIL]
    GenerateAllPagesAndFeaturesAndCheckWithVBStyleAsync(projectType: "SplitView", framework: "MVVMBasic") [FAIL]
    GenerateAllPagesAndFeaturesAndCheckWithVBStyleAsync(projectType: "SplitView", framework: "MVVMLight") [FAIL]
    GenerateAllPagesAndFeaturesAndCheckWithVBStyleAsync(projectType: "SplitView", framework: "CodeBehind") [FAIL]
    GenerateAllPagesAndFeaturesAndCheckWithVBStyleAsync(projectType: "TabbedPivot", framework: "MVVMBasic") [FAIL]
    GenerateAllPagesAndFeaturesAndCheckWithVBStyleAsync(projectType: "TabbedPivot", framework: "MVVMLight") [FAIL]
    GenerateAllPagesAndFeaturesAndCheckWithVBStyleAsync(projectType: "TabbedPivot", framework: "CodeBehind") [FAIL]

+ Process completed with exit code 9 and had 1 error(s) written to the error stream.

Find detailed information in the [build log files](https://uwpctdiags.blob.core.windows.net/buildlogs/dev.templates.tests.full_20180109.1_logs.zip)

**Comment by mrlacey** [comment] 2018-01-09 10:29
Tests pass on my machines with the VisualStudio runner. Rerunning now with the xunit console runner to try and repro

**Comment by sibille** [comment] 2018-01-09 11:05
I opened the project on the build machine and it's not building there, whilst on my machine the same project builds. I think it's sth the build machine is missing.... 
I'm having a look at it.

**Comment by mrlacey** [comment] 2018-01-09 11:27
even console runner and build script is fine on my machines. :(  

Yay. another issue with VB and the build servers! :/

**Comment by sibille** [comment] 2018-01-09 12:12
I think I found the issue, framework 4.7.1 was missing. I've just queued a new build.

**Comment by mrlacey** [comment] 2018-01-09 14:06
@sibille any news from that queued build?

**Comment by ralarcon** [comment] 2018-01-09 14:49
Currently running... no news good news :-)

**Comment by ralarcon** [comment] 2018-01-09 16:14
Fixed on dev.templates.tests.full_20180109.3!

**Closed by ralarcon** 2018-01-09 16:14 UTC
Labels: Testing, VB, bug, vsts-build

**Comment by mrlacey** [comment] 2018-01-09 16:24
Can we document the issue (even just here) so anyone running locally who hits a similar issue might know what a possible solution is.

**Comment by mrlacey** [comment] 2018-01-09 20:41
For completeness, the missing framework on the server was attributed as the cause of the failure.
