### ISSUE TITLE
Settings location in NavigationView is not at bottom of navigation pane

### ISSUE THREAD

**Issue by calloncampbell** [Microsoft/WindowsTemplateStudio#1763] opened 2018-01-29 16:51 UTC
### Repro steps

Downloaded latest WTS and create new project...select Navigation View, add Settings page and finish.

### Expected Behavior

- Settings navigation pane item should be located at the bottom of the Navigation View. Previous apps generated from WTS had this behavior.

### Actual Behavior

- Settings navigation pane item is directly after the Main page item (which is not at the bottom of the navigation view).

## System

* **VS Version: 15.5.5**
* **WTS Wizard Version: 1.6**
* **WTS Template Version: 1.6**
* **Windows Build: 1709**

**Comment by mrlacey** [comment] 2018-01-29 19:08
This is due to the way that the toolkit swaps out the HamburgerMenu for the NavigationView but doesn't map an entry to the settings view to the Settings entry in the NavigationView control. (They treat Items and OptionItems the same.)

Need to look if this is something we can influence or if a change is needed in the toolkit.

**Comment by mrlacey** [comment] 2018-02-05 21:09
I have confirmed that this is due to the way the toolkit combines the two lists (Items and OptionsItems) when using the NavigationView Control ([in this method](https://github.com/Microsoft/UWPCommunityToolkit/blob/46020ac337849f423ef10035696639489cfd9ac5/Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.cs#L139))

An ideal fix would involve changing the toolkit to be smarter about combining the lists and seeing if there was a settings item in the options list and if there was using that as the target for the AppSettings.  
Adding such a change to the toolkit is unlikely as such a check wouldn't be guaranteed to work and would instead be very focused on our needs. The Hamburger Control is also now deprecated and this is a potentially breaking change. Such a change would also take longer (based on toolkit release schedule) than we would like for a fix.

This is really the result of a change in functionality in a third-party (the toolkit) control. There is only so much we can do to work around this.  
Instead, I'm going to investigate to see if there is a simple workaround I can suggest as an alternative.

**Comment by mrlacey** [comment] 2018-02-05 23:04
The combining of the items is not something that can easily be worked around (see above comment). That said the following should get you 99% of the way to an acceptable workaround.

@calloncampbell does this help?

---

**Somewhat hacky workaround.**

Change `ShellPage.xaml` so that the existing `HamburgerMenu` control is wrapped in a Grid along with the following.

```xml
    <Grid>
        // existing HamburgerMenu goes here, unchanged
        <fcu:NavigationView
            CompactPaneLength="48"
            OpenPaneLength="320"
            CompactModeThresholdWidth="640"
            ExpandedModeThresholdWidth="1024"
            AlwaysShowHeader="False"
            SelectedItem="{x:Bind Selected, Mode=OneWay}"
            IsPaneOpen="{x:Bind IsPaneOpen, Mode=TwoWay}"
            MenuItemTemplate="{StaticResource NavigationMenuItemDataTemplate}"
            MenuItemsSource="{x:Bind PrimaryItems}"
            SelectionChanged="NavViewSelectionChanged">
            <fcu:NavigationView.HeaderTemplate>
                <DataTemplate>
                    <Grid></Grid>
                </DataTemplate>
            </fcu:NavigationView.HeaderTemplate>
            <Grid Background="{ThemeResource SystemControlBackgroundAltHighBrush}">
                <Frame x:Name="newShellFrame"/>
            </Grid>
        </fcu:NavigationView>
    </Grid>
```

The above uses an event in the code-behind for the `SelectionChanged` event, but you could use a command with something like this:

```
        <i:Interaction.Behaviors>
            <ic:EventTriggerBehavior EventName="SelectionChanged">
                <ic:InvokeCommandAction Command="{x:Bind ViewModel.NavViewItemSelectedCommand}" />
            </ic:EventTriggerBehavior>
        </i:Interaction.Behaviors>
```

Then in `ShellPage.xaml.cs` (or `ShellViewModel.cs`) change the `Initialize` method so it matches the below.

```csharp
private void Initialize()
{
    if (Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 5))
    {
        NavigationService.Frame = newShellFrame;
        NavigationMenu.Visibility = Visibility.Collapsed;
    }
    else
    {
        NavigationService.Frame = shellFrame;
    }

    NavigationService.Navigated += Frame_Navigated;
    PopulateNavItems();

    InitializeState(Window.Current.Bounds.Width);
}
```

Finally, you need to handle selecting items in the new menu. For CodeBehind it will be like this.

```csharp
private void NavViewSelectionChanged(NavigationView sender, NavigationViewSelectionChangedEventArgs args)
{
    if (DisplayMode == SplitViewDisplayMode.CompactOverlay || DisplayMode == SplitViewDisplayMode.Overlay)
    {
        IsPaneOpen = false;
    }

    if (args.IsSettingsSelected)
    {
        Navigate(_secondaryItems.First());
    }
    else
    {
        Navigate(args.SelectedItem);
    }
}
```

Or the (MVVM Basic) view model equivalent is to add the following to the view model.

```csharp
    private ICommand _navViewItemSelected;

    public ICommand NavViewItemSelectedCommand
    {
        get
        {
            if (_navViewItemSelected == null)
            {
                _navViewItemSelected = new RelayCommand<NavigationViewSelectionChangedEventArgs>(NavViewItemSelected);
            }

            return _navViewItemSelected;
        }
    }

    private void NavViewItemSelected(NavigationViewSelectionChangedEventArgs args)
    {
        if (DisplayMode == SplitViewDisplayMode.CompactOverlay || DisplayMode == SplitViewDisplayMode.Overlay)
        {
            IsPaneOpen = false;
        }

        if (args.IsSettingsSelected)
        {
            Navigate(_secondaryItems.First());
        }
        else
        {
            Navigate(args.SelectedItem);
        }
    }
```

_I've tried to do the above with the minimum amount of extra code needing to be added to the project. It may not work in all instances or for all combinations of generated project options, especially if the code has been modified significantly since it was generated. I've also tried to allow for minimum complication when switching from the toolkit's HamburgerMenu to the native NavigationView if a future change to the project allows setting the minimum supported SDK version to the FCU. The reality of such a change is many months away but I've tried to keep it in mind, but I can't be certain of everything that will be involved in such a change._  
_disclaimer over and I hope the above helps, if not please let us know how, why not, or any related issues you have._

**Comment by mrlacey** [comment] 2018-02-07 11:00
Closing this as there's nothing we can do here. 

However, please still feel free to comment here if the above workaround does not work.

**Closed by mrlacey** 2018-02-07 11:00 UTC
Labels: bug, external-issue, in-progress

**Comment by calloncampbell** [comment] 2018-02-07 13:47
I'll try this out today, thanks for the feedback and investigation.

**Comment by touseefbsb** [comment] 2018-04-08 15:43
@mrlacey  I tried this work around and I am getting a null reference exception in my **ActivationService** , **StartupAsync** method at the following line

>await Singleton<DevCenterNotificationsService>.Instance.InitializeAsync();

strangely the exception occurs at this line , but it is an unhandled exception opens as an unhandled exception by the App object. and stacktrace shows it coming from **ShellPageViewModel** bindings.

**Comment by touseefbsb** [comment] 2018-04-08 15:45
I also noticed that we r not adding any secondary items in the xaml here? so where will the settings page ( secondaryitem in hamburger menu ) will go in this workaround?

**Comment by mrlacey** [comment] 2018-04-08 15:52
@touseefbsb It seems you have a different problem to the one that originated this issue. Please open new issues for new problems.
The code in the above workaround was taken from a working project. That you are getting an error means that you are doing something different. It is rarely possible to identify the cause of an error just by providing the name of the method that is throwing an error. Please provide a minimum working repro for the exception.
The workaround above removes the automated conversion from HamburgerMenu to NavigationView and you become responsible for including the functionality you require. NavigationView doesn't have a concept of "secondary items" and so you must use an alternative solution. If this is just for settings then use the `IsSettingsVisible` property and handle its invocation accordingly.

**Comment by touseefbsb** [comment] 2018-04-08 16:10
actually I was using conditional xaml to hide away hamburger menu, but that was causing the exception in the bindings I was able to fix that by removing that conditional xaml and only using it for NavigationView.
But now I have a weird behaviour. the nav view items have some extra padding on the left side. 

![navview](https://user-images.githubusercontent.com/11542189/38469621-35717160-3b71-11e8-8980-8e7243e9b8f0.png)

**Comment by mrlacey** [comment] 2018-04-08 17:14
@touseefbsb setting conditional rules on one item and not both may lead to issues on some platforms. Make sure you test on all versions your app will run on.
Without seeing how you've specified the XAML I don't know what the issue is but I don't see a reason why setting a negative left margin wouldn't allow you to get the look you want.

**Comment by touseefbsb** [comment] 2018-04-08 17:41
@mrlacey  Yes I was able to fix this with conditional Margin on the datatemplate of navviewitem. "-16" margin on left side of the Grid ( holding all the items of nav view item template ) fixed the issue. Thanks

**Comment by touseefbsb** [comment] 2018-05-30 18:49
@mrlacey unfortunately after a long time today I was able to test my app on a creators update phone emulator and as it turns out this workaround crashes the app on creators update. the exception doesnt even get caught on normal debugging but after turning on native debugging I can get following exception : 

> Unhandled exception at 0x615F99B4 (Windows.UI.Xaml.dll) in FluentVideoPlayer.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x082318E8, 0x00000001). occurred

and it gives no details and no stacktrace at all. but from our discusions on following issue , https://github.com/Microsoft/WindowsTemplateStudio/issues/2143  , I was able to learn that my hamburger icon color issue did not need this workaround, hence I will try to remove this workaround from my app to fix the exception, but I thought it is good to inform you that this can cause such exceptions on creators update.
